// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/idp/enum.proto

package idp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppKind int32

const (
	AppKind_AppKind_Self   AppKind = 0
	AppKind_AppKind_WeChat AppKind = 1
	AppKind_AppKind_AliPay AppKind = 2
	AppKind_AppKind_Github AppKind = 3
	AppKind_AppKind_Google AppKind = 4
	AppKind_AppKind_Guest  AppKind = 1000
)

var AppKind_name = map[int32]string{
	0:    "AppKind_Self",
	1:    "AppKind_WeChat",
	2:    "AppKind_AliPay",
	3:    "AppKind_Github",
	4:    "AppKind_Google",
	1000: "AppKind_Guest",
}

var AppKind_value = map[string]int32{
	"AppKind_Self":   0,
	"AppKind_WeChat": 1,
	"AppKind_AliPay": 2,
	"AppKind_Github": 3,
	"AppKind_Google": 4,
	"AppKind_Guest":  1000,
}

func (x AppKind) String() string {
	return proto.EnumName(AppKind_name, int32(x))
}

func (AppKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{0}
}

type AppStatus int32

const (
	AppStatus_AppStatus_Normal AppStatus = 0
	AppStatus_AppStatus_Freeze AppStatus = 1
)

var AppStatus_name = map[int32]string{
	0: "AppStatus_Normal",
	1: "AppStatus_Freeze",
}

var AppStatus_value = map[string]int32{
	"AppStatus_Normal": 0,
	"AppStatus_Freeze": 1,
}

func (x AppStatus) String() string {
	return proto.EnumName(AppStatus_name, int32(x))
}

func (AppStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{1}
}

type AppGrantType int32

const (
	AppGrantType_AppGrantType_None              AppGrantType = 0
	AppGrantType_AppGrantType_ClientCredentials AppGrantType = 1
	AppGrantType_AppGrantType_AuthorizationCode AppGrantType = 2
	AppGrantType_AppGrantType_RefreshToken      AppGrantType = 4
)

var AppGrantType_name = map[int32]string{
	0: "AppGrantType_None",
	1: "AppGrantType_ClientCredentials",
	2: "AppGrantType_AuthorizationCode",
	4: "AppGrantType_RefreshToken",
}

var AppGrantType_value = map[string]int32{
	"AppGrantType_None":              0,
	"AppGrantType_ClientCredentials": 1,
	"AppGrantType_AuthorizationCode": 2,
	"AppGrantType_RefreshToken":      4,
}

func (x AppGrantType) String() string {
	return proto.EnumName(AppGrantType_name, int32(x))
}

func (AppGrantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{2}
}

type AppResponseType int32

const (
	AppResponseType_AppResponseType_None    AppResponseType = 0
	AppResponseType_AppResponseType_Code    AppResponseType = 1
	AppResponseType_AppResponseType_IdToken AppResponseType = 2
)

var AppResponseType_name = map[int32]string{
	0: "AppResponseType_None",
	1: "AppResponseType_Code",
	2: "AppResponseType_IdToken",
}

var AppResponseType_value = map[string]int32{
	"AppResponseType_None":    0,
	"AppResponseType_Code":    1,
	"AppResponseType_IdToken": 2,
}

func (x AppResponseType) String() string {
	return proto.EnumName(AppResponseType_name, int32(x))
}

func (AppResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{3}
}

type UserFlag int32

const (
	UserFlag_UserFlag_UserName  UserFlag = 0
	UserFlag_UserFlag_PhoneCode UserFlag = 1
	UserFlag_UserFlag_PhonePwd  UserFlag = 2
	UserFlag_UserFlag_EmailCode UserFlag = 3
	UserFlag_UserFlag_EmailPwd  UserFlag = 4
)

var UserFlag_name = map[int32]string{
	0: "UserFlag_UserName",
	1: "UserFlag_PhoneCode",
	2: "UserFlag_PhonePwd",
	3: "UserFlag_EmailCode",
	4: "UserFlag_EmailPwd",
}

var UserFlag_value = map[string]int32{
	"UserFlag_UserName":  0,
	"UserFlag_PhoneCode": 1,
	"UserFlag_PhonePwd":  2,
	"UserFlag_EmailCode": 3,
	"UserFlag_EmailPwd":  4,
}

func (x UserFlag) String() string {
	return proto.EnumName(UserFlag_name, int32(x))
}

func (UserFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{4}
}

type UserClaim int32

const (
	UserClaim_UserClaim_AppID     UserClaim = 0
	UserClaim_UserClaim_AppKind   UserClaim = 1
	UserClaim_UserClaim_AppName   UserClaim = 2
	UserClaim_UserClaim_ID        UserClaim = 10
	UserClaim_UserClaim_Name      UserClaim = 11
	UserClaim_UserClaim_NickName  UserClaim = 12
	UserClaim_UserClaim_IMEI      UserClaim = 13
	UserClaim_UserClaim_Duration  UserClaim = 14
	UserClaim_UserClaim_Expire    UserClaim = 15
	UserClaim_UserClaim_LoginCode UserClaim = 16
)

var UserClaim_name = map[int32]string{
	0:  "UserClaim_AppID",
	1:  "UserClaim_AppKind",
	2:  "UserClaim_AppName",
	10: "UserClaim_ID",
	11: "UserClaim_Name",
	12: "UserClaim_NickName",
	13: "UserClaim_IMEI",
	14: "UserClaim_Duration",
	15: "UserClaim_Expire",
	16: "UserClaim_LoginCode",
}

var UserClaim_value = map[string]int32{
	"UserClaim_AppID":     0,
	"UserClaim_AppKind":   1,
	"UserClaim_AppName":   2,
	"UserClaim_ID":        10,
	"UserClaim_Name":      11,
	"UserClaim_NickName":  12,
	"UserClaim_IMEI":      13,
	"UserClaim_Duration":  14,
	"UserClaim_Expire":    15,
	"UserClaim_LoginCode": 16,
}

func (x UserClaim) String() string {
	return proto.EnumName(UserClaim_name, int32(x))
}

func (UserClaim) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{5}
}

type UserGender int32

const (
	UserGender_UserGender_Girl UserGender = 0
	UserGender_UserGender_Boy  UserGender = 1
)

var UserGender_name = map[int32]string{
	0: "UserGender_Girl",
	1: "UserGender_Boy",
}

var UserGender_value = map[string]int32{
	"UserGender_Girl": 0,
	"UserGender_Boy":  1,
}

func (x UserGender) String() string {
	return proto.EnumName(UserGender_name, int32(x))
}

func (UserGender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{6}
}

type UserMFA int32

const (
	UserMFA_UserMFA_Disable UserMFA = 0
	UserMFA_UserMFA_Enable  UserMFA = 1
)

var UserMFA_name = map[int32]string{
	0: "UserMFA_Disable",
	1: "UserMFA_Enable",
}

var UserMFA_value = map[string]int32{
	"UserMFA_Disable": 0,
	"UserMFA_Enable":  1,
}

func (x UserMFA) String() string {
	return proto.EnumName(UserMFA_name, int32(x))
}

func (UserMFA) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{7}
}

type UserMFAKind int32

const (
	UserMFAKind_UserMFAKind_Phone UserMFAKind = 0
	UserMFAKind_UserMFAKind_Email UserMFAKind = 1
	UserMFAKind_UserMFAKind_Code  UserMFAKind = 2
)

var UserMFAKind_name = map[int32]string{
	0: "UserMFAKind_Phone",
	1: "UserMFAKind_Email",
	2: "UserMFAKind_Code",
}

var UserMFAKind_value = map[string]int32{
	"UserMFAKind_Phone": 0,
	"UserMFAKind_Email": 1,
	"UserMFAKind_Code":  2,
}

func (x UserMFAKind) String() string {
	return proto.EnumName(UserMFAKind_name, int32(x))
}

func (UserMFAKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{8}
}

type UserStatus int32

const (
	UserStatus_UserStatus_Normal  UserStatus = 0
	UserStatus_UserStatus_Freeze  UserStatus = 1
	UserStatus_UserStatus_Deleted UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "UserStatus_Normal",
	1: "UserStatus_Freeze",
	2: "UserStatus_Deleted",
}

var UserStatus_value = map[string]int32{
	"UserStatus_Normal":  0,
	"UserStatus_Freeze":  1,
	"UserStatus_Deleted": 2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{9}
}

type UserRolesEditKind int32

const (
	UserRolesEditKind_UserRolesEditKind_Add UserRolesEditKind = 0
	UserRolesEditKind_UserRolesEditKind_Del UserRolesEditKind = 1
)

var UserRolesEditKind_name = map[int32]string{
	0: "UserRolesEditKind_Add",
	1: "UserRolesEditKind_Del",
}

var UserRolesEditKind_value = map[string]int32{
	"UserRolesEditKind_Add": 0,
	"UserRolesEditKind_Del": 1,
}

func (x UserRolesEditKind) String() string {
	return proto.EnumName(UserRolesEditKind_name, int32(x))
}

func (UserRolesEditKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30fa8b490d2ebd77, []int{10}
}

func init() {
	proto.RegisterEnum("idp.AppKind", AppKind_name, AppKind_value)
	proto.RegisterEnum("idp.AppStatus", AppStatus_name, AppStatus_value)
	proto.RegisterEnum("idp.AppGrantType", AppGrantType_name, AppGrantType_value)
	proto.RegisterEnum("idp.AppResponseType", AppResponseType_name, AppResponseType_value)
	proto.RegisterEnum("idp.UserFlag", UserFlag_name, UserFlag_value)
	proto.RegisterEnum("idp.UserClaim", UserClaim_name, UserClaim_value)
	proto.RegisterEnum("idp.UserGender", UserGender_name, UserGender_value)
	proto.RegisterEnum("idp.UserMFA", UserMFA_name, UserMFA_value)
	proto.RegisterEnum("idp.UserMFAKind", UserMFAKind_name, UserMFAKind_value)
	proto.RegisterEnum("idp.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("idp.UserRolesEditKind", UserRolesEditKind_name, UserRolesEditKind_value)
}

func init() { proto.RegisterFile("hlm-ipfs/proto/idp/enum.proto", fileDescriptor_30fa8b490d2ebd77) }

var fileDescriptor_30fa8b490d2ebd77 = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdf, 0x4f, 0x14, 0x31,
	0x10, 0xc7, 0x6f, 0x0f, 0x14, 0x19, 0x7e, 0x8d, 0x05, 0x44, 0x62, 0xf0, 0xc1, 0xc7, 0x4d, 0x94,
	0x44, 0x63, 0x7c, 0x5e, 0xee, 0x57, 0x2e, 0x0a, 0xc1, 0x03, 0x63, 0xe2, 0xcb, 0x66, 0xcf, 0x1d,
	0xb8, 0x86, 0x5e, 0xdb, 0x74, 0x7b, 0x51, 0x78, 0xe1, 0x1f, 0xf0, 0xff, 0xd4, 0x3f, 0xc3, 0xb4,
	0xbb, 0xbd, 0xbd, 0x3d, 0x78, 0xeb, 0x7c, 0xe6, 0x3b, 0xed, 0xb4, 0x33, 0x53, 0x38, 0x9a, 0x88,
	0xe9, 0x5b, 0xae, 0xaf, 0x8a, 0x63, 0x6d, 0x94, 0x55, 0xc7, 0x3c, 0xd7, 0xc7, 0x24, 0x67, 0xd3,
	0x77, 0xde, 0x64, 0x2b, 0x3c, 0xd7, 0xf1, 0x3d, 0xac, 0x25, 0x5a, 0x7f, 0xe6, 0x32, 0x67, 0x08,
	0x9b, 0xd5, 0x32, 0xbd, 0x20, 0x71, 0x85, 0x2d, 0xc6, 0x60, 0x3b, 0x90, 0xef, 0xd4, 0x99, 0x64,
	0x16, 0xa3, 0x45, 0x96, 0x08, 0x7e, 0x9e, 0xdd, 0x62, 0x7b, 0x91, 0x0d, 0xb8, 0x9d, 0xcc, 0xc6,
	0xb8, 0xd2, 0x60, 0x4a, 0x5d, 0x0b, 0xc2, 0x55, 0xc6, 0x60, 0x6b, 0xce, 0x66, 0x54, 0x58, 0xfc,
	0xb7, 0x16, 0x7f, 0x82, 0xf5, 0x44, 0xeb, 0x0b, 0x9b, 0xd9, 0x59, 0xc1, 0xf6, 0x00, 0xe7, 0x46,
	0x7a, 0xa6, 0xcc, 0x34, 0x13, 0xd8, 0x6a, 0xd2, 0xbe, 0x21, 0xba, 0x23, 0x8c, 0xe2, 0x3f, 0x91,
	0xcf, 0x77, 0x60, 0x32, 0x69, 0x2f, 0x6f, 0x35, 0xb1, 0x7d, 0x78, 0xbe, 0x68, 0xa7, 0x67, 0x4a,
	0x12, 0xb6, 0xd8, 0x1b, 0x78, 0xdd, 0xc0, 0x1d, 0xc1, 0x49, 0xda, 0x8e, 0xa1, 0x9c, 0xa4, 0xe5,
	0x99, 0x28, 0x30, 0x7a, 0xa0, 0x49, 0x66, 0x76, 0xa2, 0x0c, 0xbf, 0xcb, 0x2c, 0x57, 0xb2, 0xa3,
	0x72, 0xc2, 0x36, 0x3b, 0x82, 0xc3, 0x86, 0x66, 0x44, 0x57, 0x86, 0x8a, 0xc9, 0xa5, 0xba, 0x21,
	0x89, 0xab, 0xf1, 0x18, 0x76, 0x12, 0xad, 0x47, 0x54, 0x68, 0x25, 0x0b, 0xf2, 0x09, 0xbd, 0x84,
	0xbd, 0x25, 0x14, 0x72, 0x7a, 0xc4, 0xe3, 0x4f, 0x89, 0xd8, 0x2b, 0x38, 0x58, 0xf6, 0x0c, 0xf3,
	0xf2, 0x8c, 0x76, 0x7c, 0x0f, 0xcf, 0xbe, 0x15, 0x64, 0xfa, 0x22, 0xbb, 0x76, 0xb7, 0x0d, 0xeb,
	0xd4, 0x2d, 0xce, 0xb2, 0xa9, 0xdb, 0xf9, 0x05, 0xb0, 0x39, 0x3e, 0x9f, 0x28, 0x49, 0xd5, 0xbe,
	0x8b, 0x72, 0xcf, 0xcf, 0x7f, 0xe5, 0xd8, 0x6e, 0xc8, 0x7b, 0xd3, 0x8c, 0x0b, 0x2f, 0x5f, 0x69,
	0xc8, 0x3d, 0x77, 0xf2, 0xd5, 0xf8, 0x6f, 0x04, 0xeb, 0x8e, 0x77, 0x44, 0xc6, 0xa7, 0x6c, 0x17,
	0x76, 0xe6, 0x46, 0x9a, 0x68, 0x3d, 0xec, 0x62, 0x2b, 0x44, 0xce, 0xa1, 0xab, 0x76, 0x7d, 0xfe,
	0x1c, 0xfb, 0x74, 0xdb, 0xae, 0xe7, 0x6a, 0x3c, 0xec, 0x22, 0xb8, 0xbe, 0xa9, 0x89, 0x57, 0x6d,
	0x84, 0x2c, 0x2b, 0xc6, 0x7f, 0xde, 0x78, 0xbe, 0xd9, 0xd4, 0x0e, 0x4f, 0x7b, 0x43, 0xdc, 0x6a,
	0x6a, 0xbb, 0x33, 0xe3, 0x4b, 0x88, 0xdb, 0xae, 0x89, 0x6a, 0xde, 0xfb, 0xad, 0xb9, 0x21, 0xdc,
	0x61, 0x07, 0xb0, 0x5b, 0xd3, 0x2f, 0xea, 0x9a, 0x97, 0xd5, 0xc6, 0xf8, 0x23, 0x80, 0x73, 0x0c,
	0x48, 0xe6, 0x64, 0xc2, 0x4d, 0x4b, 0x2b, 0x1d, 0x70, 0x23, 0xca, 0xe9, 0x58, 0x80, 0x27, 0xea,
	0x16, 0xa3, 0xf8, 0x3d, 0xac, 0x39, 0x76, 0xda, 0x4f, 0x42, 0xcc, 0x69, 0x3f, 0x49, 0xbb, 0xbc,
	0xc8, 0xc6, 0x82, 0xea, 0x18, 0x07, 0x7b, 0xd2, 0xb3, 0x28, 0xfe, 0x0a, 0x1b, 0x15, 0xf3, 0x63,
	0x58, 0xbd, 0x54, 0x65, 0x96, 0xc5, 0xaa, 0xdf, 0x35, 0x60, 0x5f, 0x14, 0x8c, 0xc2, 0xb5, 0x02,
	0x2e, 0x7b, 0x35, 0x1e, 0x95, 0xd9, 0x57, 0x53, 0x55, 0x85, 0x2e, 0x8f, 0x55, 0x13, 0x87, 0xb9,
	0x0a, 0x0f, 0x58, 0xe1, 0x2e, 0x09, 0xb2, 0x94, 0x63, 0x3b, 0x1e, 0x96, 0xf2, 0x91, 0x12, 0x54,
	0xf4, 0x72, 0x6e, 0x7d, 0xb2, 0x87, 0xb0, 0xff, 0x00, 0xa6, 0x49, 0x9e, 0x63, 0xeb, 0x71, 0x57,
	0x97, 0x04, 0x46, 0x27, 0x4f, 0x7e, 0xb8, 0xbf, 0x67, 0xfc, 0xd4, 0xff, 0x43, 0x1f, 0xfe, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xc2, 0xc4, 0xa7, 0xf3, 0xa8, 0x04, 0x00, 0x00,
}
