// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/idp/model.idp.proto

package idp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basic "hlm-ipfs/sdk/proto/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthorizeRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeRequest) Reset()         { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()    {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{0}
}

func (m *AuthorizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeRequest.Unmarshal(m, b)
}
func (m *AuthorizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeRequest.Merge(m, src)
}
func (m *AuthorizeRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizeRequest.Size(m)
}
func (m *AuthorizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeRequest proto.InternalMessageInfo

func (m *AuthorizeRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AuthorizeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GuestRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	GuestID              string   `protobuf:"bytes,2,opt,name=GuestID,proto3" json:"GuestID,omitempty"`
	GuestName            string   `protobuf:"bytes,3,opt,name=GuestName,proto3" json:"GuestName,omitempty"`
	IMEI                 string   `protobuf:"bytes,10,opt,name=IMEI,proto3" json:"IMEI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestRequest) Reset()         { *m = GuestRequest{} }
func (m *GuestRequest) String() string { return proto.CompactTextString(m) }
func (*GuestRequest) ProtoMessage()    {}
func (*GuestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{1}
}

func (m *GuestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestRequest.Unmarshal(m, b)
}
func (m *GuestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestRequest.Marshal(b, m, deterministic)
}
func (m *GuestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestRequest.Merge(m, src)
}
func (m *GuestRequest) XXX_Size() int {
	return xxx_messageInfo_GuestRequest.Size(m)
}
func (m *GuestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GuestRequest proto.InternalMessageInfo

func (m *GuestRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *GuestRequest) GetGuestID() string {
	if m != nil {
		return m.GuestID
	}
	return ""
}

func (m *GuestRequest) GetGuestName() string {
	if m != nil {
		return m.GuestName
	}
	return ""
}

func (m *GuestRequest) GetIMEI() string {
	if m != nil {
		return m.IMEI
	}
	return ""
}

type LoginByUserNameRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	VerifyCode           string   `protobuf:"bytes,3,opt,name=VerifyCode,proto3" json:"VerifyCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginByUserNameRequest) Reset()         { *m = LoginByUserNameRequest{} }
func (m *LoginByUserNameRequest) String() string { return proto.CompactTextString(m) }
func (*LoginByUserNameRequest) ProtoMessage()    {}
func (*LoginByUserNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{2}
}

func (m *LoginByUserNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByUserNameRequest.Unmarshal(m, b)
}
func (m *LoginByUserNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByUserNameRequest.Marshal(b, m, deterministic)
}
func (m *LoginByUserNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByUserNameRequest.Merge(m, src)
}
func (m *LoginByUserNameRequest) XXX_Size() int {
	return xxx_messageInfo_LoginByUserNameRequest.Size(m)
}
func (m *LoginByUserNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByUserNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByUserNameRequest proto.InternalMessageInfo

func (m *LoginByUserNameRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginByUserNameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginByUserNameRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

type LoginRequest struct {
	AppID                string                  `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	Device               *DeviceInfo             `protobuf:"bytes,2,opt,name=Device,proto3" json:"Device,omitempty"`
	UserPassword         *LoginByUserNameRequest `protobuf:"bytes,3,opt,name=UserPassword,proto3" json:"UserPassword,omitempty"`
	PhoneCode            *basic.KVStringAtString `protobuf:"bytes,4,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	PhonePassword        *basic.KVStringAtString `protobuf:"bytes,5,opt,name=PhonePassword,proto3" json:"PhonePassword,omitempty"`
	EmailCode            *basic.KVStringAtString `protobuf:"bytes,6,opt,name=EmailCode,proto3" json:"EmailCode,omitempty"`
	EmailPassword        *basic.KVStringAtString `protobuf:"bytes,7,opt,name=EmailPassword,proto3" json:"EmailPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *LoginRequest) GetDevice() *DeviceInfo {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *LoginRequest) GetUserPassword() *LoginByUserNameRequest {
	if m != nil {
		return m.UserPassword
	}
	return nil
}

func (m *LoginRequest) GetPhoneCode() *basic.KVStringAtString {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *LoginRequest) GetPhonePassword() *basic.KVStringAtString {
	if m != nil {
		return m.PhonePassword
	}
	return nil
}

func (m *LoginRequest) GetEmailCode() *basic.KVStringAtString {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

func (m *LoginRequest) GetEmailPassword() *basic.KVStringAtString {
	if m != nil {
		return m.EmailPassword
	}
	return nil
}

type MFALoginRequest struct {
	Token                string                  `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Kind                 UserMFAKind             `protobuf:"varint,2,opt,name=Kind,proto3,enum=idp.UserMFAKind" json:"Kind,omitempty"`
	Code                 *basic.KVStringAtString `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MFALoginRequest) Reset()         { *m = MFALoginRequest{} }
func (m *MFALoginRequest) String() string { return proto.CompactTextString(m) }
func (*MFALoginRequest) ProtoMessage()    {}
func (*MFALoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{4}
}

func (m *MFALoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MFALoginRequest.Unmarshal(m, b)
}
func (m *MFALoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MFALoginRequest.Marshal(b, m, deterministic)
}
func (m *MFALoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MFALoginRequest.Merge(m, src)
}
func (m *MFALoginRequest) XXX_Size() int {
	return xxx_messageInfo_MFALoginRequest.Size(m)
}
func (m *MFALoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MFALoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MFALoginRequest proto.InternalMessageInfo

func (m *MFALoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MFALoginRequest) GetKind() UserMFAKind {
	if m != nil {
		return m.Kind
	}
	return UserMFAKind_UserMFAKind_Phone
}

func (m *MFALoginRequest) GetCode() *basic.KVStringAtString {
	if m != nil {
		return m.Code
	}
	return nil
}

type LoginResponse struct {
	MFAToken             string   `protobuf:"bytes,1,opt,name=MFAToken,proto3" json:"MFAToken,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	Newcomer             bool     `protobuf:"varint,10,opt,name=Newcomer,proto3" json:"Newcomer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetMFAToken() string {
	if m != nil {
		return m.MFAToken
	}
	return ""
}

func (m *LoginResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginResponse) GetNewcomer() bool {
	if m != nil {
		return m.Newcomer
	}
	return false
}

type ChangePasswordRequest struct {
	Password             string                  `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	PhoneCode            *basic.KVStringAtString `protobuf:"bytes,2,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	EmailCode            *basic.KVStringAtString `protobuf:"bytes,3,opt,name=EmailCode,proto3" json:"EmailCode,omitempty"`
	NewPassword          string                  `protobuf:"bytes,10,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	ConfirmPassword      string                  `protobuf:"bytes,11,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{6}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetPhoneCode() *basic.KVStringAtString {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *ChangePasswordRequest) GetEmailCode() *basic.KVStringAtString {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type ForgetPasswordRequest struct {
	AppID                string                  `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	PhoneCode            *basic.KVStringAtString `protobuf:"bytes,2,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	EmailCode            *basic.KVStringAtString `protobuf:"bytes,3,opt,name=EmailCode,proto3" json:"EmailCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ForgetPasswordRequest) Reset()         { *m = ForgetPasswordRequest{} }
func (m *ForgetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{7}
}

func (m *ForgetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordRequest.Size(m)
}
func (m *ForgetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *ForgetPasswordRequest) GetPhoneCode() *basic.KVStringAtString {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *ForgetPasswordRequest) GetEmailCode() *basic.KVStringAtString {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

type SettingRequest struct {
	Name                 *basic.String           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NickName             *basic.String           `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Motto                *basic.String           `protobuf:"bytes,3,opt,name=Motto,proto3" json:"Motto,omitempty"`
	Avatar               *basic.String           `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Address              *basic.String           `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Gender               *basic.Int32            `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Birthday             *basic.Int64            `protobuf:"bytes,7,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	PhoneCode            *basic.KVStringAtString `protobuf:"bytes,8,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	EmailCode            *basic.KVStringAtString `protobuf:"bytes,9,opt,name=EmailCode,proto3" json:"EmailCode,omitempty"`
	MFA                  *basic.Bool             `protobuf:"bytes,10,opt,name=MFA,proto3" json:"MFA,omitempty"`
	MFAKind              *basic.Int32            `protobuf:"bytes,11,opt,name=MFAKind,proto3" json:"MFAKind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SettingRequest) Reset()         { *m = SettingRequest{} }
func (m *SettingRequest) String() string { return proto.CompactTextString(m) }
func (*SettingRequest) ProtoMessage()    {}
func (*SettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{8}
}

func (m *SettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingRequest.Unmarshal(m, b)
}
func (m *SettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingRequest.Marshal(b, m, deterministic)
}
func (m *SettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingRequest.Merge(m, src)
}
func (m *SettingRequest) XXX_Size() int {
	return xxx_messageInfo_SettingRequest.Size(m)
}
func (m *SettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SettingRequest proto.InternalMessageInfo

func (m *SettingRequest) GetName() *basic.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *SettingRequest) GetNickName() *basic.String {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *SettingRequest) GetMotto() *basic.String {
	if m != nil {
		return m.Motto
	}
	return nil
}

func (m *SettingRequest) GetAvatar() *basic.String {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *SettingRequest) GetAddress() *basic.String {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SettingRequest) GetGender() *basic.Int32 {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *SettingRequest) GetBirthday() *basic.Int64 {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *SettingRequest) GetPhoneCode() *basic.KVStringAtString {
	if m != nil {
		return m.PhoneCode
	}
	return nil
}

func (m *SettingRequest) GetEmailCode() *basic.KVStringAtString {
	if m != nil {
		return m.EmailCode
	}
	return nil
}

func (m *SettingRequest) GetMFA() *basic.Bool {
	if m != nil {
		return m.MFA
	}
	return nil
}

func (m *SettingRequest) GetMFAKind() *basic.Int32 {
	if m != nil {
		return m.MFAKind
	}
	return nil
}

type UserInfo struct {
	ID                   int64      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	NickName             string     `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Motto                string     `protobuf:"bytes,4,opt,name=Motto,proto3" json:"Motto,omitempty"`
	Avatar               string     `protobuf:"bytes,5,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender               UserGender `protobuf:"varint,6,opt,name=Gender,proto3,enum=idp.UserGender" json:"Gender,omitempty"`
	Address              string     `protobuf:"bytes,7,opt,name=Address,proto3" json:"Address,omitempty"`
	AppID                string     `protobuf:"bytes,100,opt,name=AppID,proto3" json:"AppID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{9}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfo) GetMotto() string {
	if m != nil {
		return m.Motto
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetGender() UserGender {
	if m != nil {
		return m.Gender
	}
	return UserGender_UserGender_Girl
}

func (m *UserInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserInfo) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type UsersResponse struct {
	Total                int32       `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Items                []*UserInfo `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{10}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UsersResponse) GetItems() []*UserInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type SearchRequest struct {
	Index                int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Words                []string `protobuf:"bytes,3,rep,name=Words,proto3" json:"Words,omitempty"`
	Phones               []string `protobuf:"bytes,4,rep,name=Phones,proto3" json:"Phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{11}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SearchRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchRequest) GetWords() []string {
	if m != nil {
		return m.Words
	}
	return nil
}

func (m *SearchRequest) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

type SearchResponse struct {
	Total                int32                `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Items                []*UserInfo          `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	PhonesUsers          map[string]*UserInfo `protobuf:"bytes,3,rep,name=PhonesUsers,proto3" json:"PhonesUsers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4c91bd56c7f41c1, []int{12}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchResponse) GetItems() []*UserInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SearchResponse) GetPhonesUsers() map[string]*UserInfo {
	if m != nil {
		return m.PhonesUsers
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthorizeRequest)(nil), "idp.AuthorizeRequest")
	proto.RegisterType((*GuestRequest)(nil), "idp.GuestRequest")
	proto.RegisterType((*LoginByUserNameRequest)(nil), "idp.LoginByUserNameRequest")
	proto.RegisterType((*LoginRequest)(nil), "idp.LoginRequest")
	proto.RegisterType((*MFALoginRequest)(nil), "idp.MFALoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "idp.LoginResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "idp.ChangePasswordRequest")
	proto.RegisterType((*ForgetPasswordRequest)(nil), "idp.ForgetPasswordRequest")
	proto.RegisterType((*SettingRequest)(nil), "idp.SettingRequest")
	proto.RegisterType((*UserInfo)(nil), "idp.UserInfo")
	proto.RegisterType((*UsersResponse)(nil), "idp.UsersResponse")
	proto.RegisterType((*SearchRequest)(nil), "idp.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "idp.SearchResponse")
	proto.RegisterMapType((map[string]*UserInfo)(nil), "idp.SearchResponse.PhonesUsersEntry")
}

func init() { proto.RegisterFile("hlm-ipfs/proto/idp/model.idp.proto", fileDescriptor_c4c91bd56c7f41c1) }

var fileDescriptor_c4c91bd56c7f41c1 = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x97, 0xe3, 0xfc, 0xeb, 0x24, 0x69, 0xab, 0xd5, 0x5d, 0x89, 0x0a, 0x77, 0x0a, 0xa6, 0x70,
	0x45, 0x88, 0x56, 0xca, 0x01, 0x42, 0x48, 0x08, 0xdc, 0x3f, 0x39, 0x99, 0x23, 0xd5, 0xc9, 0x81,
	0x43, 0xe2, 0xcd, 0x17, 0x6f, 0x12, 0xab, 0xb1, 0xd7, 0xec, 0xba, 0x2d, 0xe9, 0x57, 0xe1, 0x99,
	0x0f, 0xc4, 0x1b, 0xcf, 0xbc, 0xf3, 0x05, 0x78, 0x42, 0x3b, 0xbb, 0xde, 0xd8, 0x26, 0xf4, 0x2a,
	0x90, 0xee, 0xa5, 0xf5, 0xcc, 0xfc, 0x66, 0x7f, 0xb3, 0xf3, 0x6f, 0x03, 0xce, 0x62, 0x19, 0x7f,
	0x1c, 0xa5, 0x33, 0x71, 0x9c, 0x72, 0x96, 0xb1, 0xe3, 0x28, 0x4c, 0x8f, 0x63, 0x16, 0xd2, 0xe5,
	0x51, 0x14, 0xa6, 0x47, 0xa8, 0x23, 0x76, 0x14, 0xa6, 0xfb, 0x83, 0x0a, 0xf0, 0x55, 0x20, 0xa2,
	0xa9, 0xfa, 0xab, 0x60, 0xfb, 0x8f, 0xff, 0xf5, 0x28, 0x65, 0x7f, 0xb4, 0xc1, 0x4e, 0x93, 0xab,
	0x58, 0x99, 0x9d, 0xaf, 0x61, 0xd7, 0xbd, 0xca, 0x16, 0x8c, 0x47, 0xb7, 0xd4, 0xa7, 0x3f, 0x5d,
	0x51, 0x91, 0x91, 0x3e, 0xb4, 0x26, 0x94, 0x5f, 0x47, 0x53, 0xda, 0xb7, 0x06, 0xd6, 0xe1, 0x96,
	0x9f, 0x8b, 0x84, 0x40, 0xfd, 0x22, 0x88, 0x69, 0xbf, 0x86, 0x6a, 0xfc, 0x76, 0x52, 0xe8, 0x3e,
	0x93, 0x6e, 0xb9, 0xf7, 0x03, 0x68, 0xb8, 0x69, 0xea, 0x9d, 0x69, 0x5f, 0x25, 0xc8, 0x33, 0x11,
	0xe5, 0x9d, 0x69, 0xe7, 0x5c, 0x24, 0xef, 0xc0, 0x16, 0x7e, 0xe2, 0xc1, 0x36, 0xda, 0xd6, 0x0a,
	0xc9, 0xe8, 0x8d, 0xcf, 0xbd, 0x3e, 0x28, 0x46, 0xf9, 0xed, 0xa4, 0xb0, 0xf7, 0x2d, 0x9b, 0x47,
	0xc9, 0xc9, 0xea, 0x7b, 0x41, 0xb9, 0x84, 0xe5, 0xdc, 0xfb, 0xd0, 0xce, 0x55, 0x9a, 0xde, 0xc8,
	0xd2, 0xf6, 0x22, 0x10, 0xe2, 0x86, 0xf1, 0x50, 0x87, 0x60, 0x64, 0xf2, 0x18, 0xe0, 0x25, 0xe5,
	0xd1, 0x6c, 0x75, 0xca, 0xc2, 0x3c, 0x88, 0x82, 0xc6, 0xf9, 0xab, 0x06, 0x5d, 0xa4, 0xbc, 0xfb,
	0x92, 0x4f, 0xa0, 0x79, 0x46, 0x31, 0x6f, 0x92, 0xa0, 0x33, 0xdc, 0xc1, 0x72, 0x2a, 0x95, 0x97,
	0xcc, 0x98, 0xaf, 0xcd, 0xe4, 0x2b, 0xe8, 0xca, 0xb8, 0x4c, 0x3c, 0x36, 0xc2, 0xdf, 0x46, 0xf8,
	0xe6, 0xab, 0xf9, 0x25, 0x07, 0xf2, 0x29, 0x6c, 0xbd, 0x58, 0xb0, 0x84, 0x62, 0xbc, 0x75, 0xf4,
	0x7e, 0xeb, 0x48, 0xb5, 0xc5, 0xf3, 0x97, 0x93, 0x8c, 0x47, 0xc9, 0xdc, 0xcd, 0xd4, 0x7f, 0x7f,
	0x8d, 0x24, 0x5f, 0x42, 0x0f, 0x05, 0x43, 0xdc, 0xb8, 0xdb, 0xb5, 0x8c, 0x96, 0xac, 0xe7, 0x71,
	0x10, 0x2d, 0x91, 0xb5, 0xf9, 0x1a, 0x56, 0x83, 0x94, 0xac, 0x28, 0x18, 0xd6, 0xd6, 0x6b, 0x58,
	0x4b, 0x68, 0xe7, 0x16, 0x76, 0xc6, 0x23, 0xb7, 0x9a, 0xfe, 0xef, 0xd8, 0x25, 0x4d, 0xf2, 0xf4,
	0xa3, 0x40, 0x0e, 0xa0, 0xfe, 0x3c, 0x4a, 0x54, 0x75, 0xb7, 0x87, 0xbb, 0x98, 0x4d, 0x99, 0xb5,
	0xf1, 0xc8, 0x95, 0x7a, 0x1f, 0xad, 0xe4, 0x23, 0xa8, 0x9b, 0x2a, 0xdf, 0x11, 0x04, 0x82, 0x9c,
	0x5f, 0x2d, 0xe8, 0x69, 0x66, 0x91, 0xb2, 0x44, 0x60, 0x1b, 0x8d, 0x47, 0x6e, 0x91, 0xdd, 0xc8,
	0x64, 0x0f, 0x9a, 0x92, 0x4f, 0xf7, 0xb8, 0xed, 0x6b, 0x89, 0x0c, 0xa0, 0xe3, 0x4e, 0xa7, 0x54,
	0x08, 0xe5, 0xa6, 0xfa, 0xab, 0xa8, 0x22, 0x0e, 0x74, 0x7d, 0x3a, 0xe3, 0x54, 0x2c, 0x14, 0xa4,
	0x8e, 0x90, 0x92, 0x4e, 0x32, 0x5f, 0xd0, 0x9b, 0x29, 0x8b, 0x29, 0xc7, 0x71, 0x68, 0xfb, 0x46,
	0x76, 0xfe, 0xb4, 0xe0, 0xe1, 0xe9, 0x22, 0x48, 0xe6, 0xa6, 0x58, 0x85, 0x91, 0x30, 0x79, 0xb7,
	0x2a, 0x6d, 0x5f, 0xea, 0xa2, 0xda, 0xbd, 0xbb, 0xa8, 0xd4, 0x06, 0xf6, 0xbd, 0xdb, 0x60, 0x00,
	0x9d, 0x0b, 0x7a, 0x63, 0x82, 0x51, 0x13, 0x5d, 0x54, 0x91, 0x43, 0xd8, 0x39, 0x65, 0xc9, 0x2c,
	0xe2, 0xb1, 0x41, 0x75, 0x10, 0x55, 0x55, 0x3b, 0xbf, 0x58, 0xf0, 0x70, 0xc4, 0xf8, 0x9c, 0x66,
	0xd5, 0xfb, 0x6e, 0x9e, 0xcc, 0x37, 0x7a, 0x53, 0xe7, 0x77, 0x1b, 0xb6, 0x27, 0x34, 0xcb, 0xa4,
	0x5a, 0x87, 0xf5, 0xae, 0xde, 0x9c, 0x16, 0x1e, 0xd2, 0xd3, 0x87, 0xe4, 0xbd, 0x86, 0x0b, 0xea,
	0x43, 0x68, 0x5f, 0x44, 0xd3, 0x4b, 0xb3, 0x60, 0xff, 0x01, 0x33, 0x66, 0xf2, 0x1e, 0x34, 0xc6,
	0x2c, 0xcb, 0x98, 0x8e, 0xa9, 0x82, 0x53, 0x36, 0xf2, 0x3e, 0x34, 0xdd, 0xeb, 0x20, 0x0b, 0xb8,
	0x5e, 0x10, 0x15, 0x94, 0x36, 0x92, 0x27, 0xd0, 0x72, 0xc3, 0x90, 0x53, 0x21, 0xf4, 0x36, 0xa8,
	0xe0, 0x72, 0x2b, 0x39, 0x80, 0xe6, 0x33, 0x9a, 0x84, 0x94, 0xeb, 0xd1, 0xef, 0x6a, 0x9c, 0x97,
	0x64, 0x4f, 0x87, 0xbe, 0xb6, 0x91, 0x43, 0x68, 0x9f, 0x44, 0x3c, 0x5b, 0x84, 0xc1, 0x4a, 0xcf,
	0x79, 0x01, 0xf7, 0xd9, 0x27, 0xbe, 0xb1, 0x96, 0x6b, 0xd2, 0xfe, 0x6f, 0x35, 0xd9, 0xba, 0x77,
	0xf7, 0x3d, 0x02, 0x7b, 0x3c, 0x72, 0xb1, 0xeb, 0x3a, 0xc3, 0x8e, 0x76, 0x38, 0x61, 0x6c, 0xe9,
	0x4b, 0x3d, 0xf9, 0x00, 0x5a, 0x7a, 0x4d, 0x60, 0xcb, 0x55, 0x6f, 0x97, 0x1b, 0x9d, 0xdf, 0x2c,
	0xf5, 0xc4, 0xc8, 0x75, 0x4e, 0xb6, 0xa1, 0xa6, 0x1b, 0xcd, 0xf6, 0x6b, 0xde, 0xd9, 0xa6, 0xe7,
	0x11, 0xa7, 0x36, 0xaf, 0xaa, 0x1a, 0xfc, 0x75, 0x19, 0x1f, 0xe4, 0x65, 0x54, 0xe3, 0xae, 0xeb,
	0xb6, 0x67, 0xea, 0xd6, 0x40, 0xf5, 0xba, 0x50, 0xc5, 0xfc, 0x6f, 0xeb, 0xd7, 0x45, 0x06, 0xa3,
	0xd4, 0xa6, 0x04, 0xfd, 0x75, 0x45, 0x5b, 0xea, 0xad, 0xcd, 0x4b, 0x68, 0x86, 0x23, 0x2c, 0x0c,
	0x87, 0xf3, 0x0d, 0xf4, 0xe4, 0x29, 0xc2, 0xec, 0x38, 0x5c, 0xaf, 0x59, 0xb0, 0xc4, 0xab, 0x35,
	0x7c, 0x25, 0xc8, 0xa6, 0xf3, 0x32, 0x1a, 0x8b, 0x7e, 0x6d, 0x60, 0x63, 0x9b, 0xe4, 0xf4, 0xf8,
	0xb4, 0x29, 0x9b, 0x33, 0x87, 0xde, 0x84, 0x06, 0x7c, 0xba, 0x28, 0xcc, 0xa3, 0x97, 0x84, 0xf4,
	0xe7, 0xfc, 0x2c, 0x14, 0x64, 0xa6, 0x26, 0xd1, 0xad, 0xca, 0x54, 0xc3, 0xc7, 0x6f, 0x89, 0xfc,
	0x81, 0xf1, 0x50, 0xf4, 0xed, 0x81, 0x2d, 0x83, 0x43, 0x41, 0x66, 0x03, 0x6b, 0x2f, 0xfa, 0x75,
	0x54, 0x6b, 0xc9, 0xf9, 0xc3, 0x92, 0x33, 0xa6, 0x98, 0xfe, 0x77, 0xd8, 0x64, 0x04, 0x1d, 0x75,
	0x2e, 0x26, 0x02, 0x23, 0xe8, 0x0c, 0x0f, 0x10, 0x5a, 0x26, 0x39, 0x2a, 0xc0, 0xce, 0x93, 0x8c,
	0xaf, 0xfc, 0xa2, 0xe3, 0xfe, 0x18, 0x76, 0xab, 0x00, 0xb2, 0x0b, 0xf6, 0x25, 0x5d, 0xe9, 0x7d,
	0x24, 0x3f, 0x65, 0x48, 0xd7, 0xc1, 0xf2, 0x6a, 0x3d, 0xe6, 0xe5, 0x90, 0xd0, 0xf6, 0x45, 0xed,
	0x73, 0xeb, 0xa4, 0xf1, 0xa3, 0xfc, 0x15, 0xf8, 0xaa, 0x89, 0xbf, 0xd5, 0x9e, 0xfe, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x62, 0x5a, 0xa8, 0x5e, 0x37, 0x0a, 0x00, 0x00,
}
