// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/idp/model.proto

package idp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceInfo struct {
	IMEI                 string   `protobuf:"bytes,1,opt,name=IMEI,proto3" json:"IMEI,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=Model,proto3" json:"Model,omitempty"`
	OSName               string   `protobuf:"bytes,4,opt,name=OSName,proto3" json:"OSName,omitempty"`
	OSVersion            string   `protobuf:"bytes,5,opt,name=OSVersion,proto3" json:"OSVersion,omitempty"`
	AppName              string   `protobuf:"bytes,6,opt,name=AppName,proto3" json:"AppName,omitempty"`
	AppVersion           string   `protobuf:"bytes,7,opt,name=AppVersion,proto3" json:"AppVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf7b7d3df3556c9, []int{0}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetIMEI() string {
	if m != nil {
		return m.IMEI
	}
	return ""
}

func (m *DeviceInfo) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *DeviceInfo) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *DeviceInfo) GetOSName() string {
	if m != nil {
		return m.OSName
	}
	return ""
}

func (m *DeviceInfo) GetOSVersion() string {
	if m != nil {
		return m.OSVersion
	}
	return ""
}

func (m *DeviceInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *DeviceInfo) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

type ProfileInfo struct {
	AppID                string      `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	AppKind              AppKind     `protobuf:"varint,2,opt,name=AppKind,proto3,enum=idp.AppKind" json:"AppKind,omitempty"`
	AppName              string      `protobuf:"bytes,3,opt,name=AppName,proto3" json:"AppName,omitempty"`
	Flag                 UserFlag    `protobuf:"varint,4,opt,name=Flag,proto3,enum=idp.UserFlag" json:"Flag,omitempty"`
	ID                   int64       `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string      `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	NickName             string      `protobuf:"bytes,7,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Motto                string      `protobuf:"bytes,8,opt,name=Motto,proto3" json:"Motto,omitempty"`
	Phone                string      `protobuf:"bytes,9,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string      `protobuf:"bytes,10,opt,name=Email,proto3" json:"Email,omitempty"`
	Avatar               string      `protobuf:"bytes,11,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Address              string      `protobuf:"bytes,12,opt,name=Address,proto3" json:"Address,omitempty"`
	Gender               UserGender  `protobuf:"varint,13,opt,name=Gender,proto3,enum=idp.UserGender" json:"Gender,omitempty"`
	MFA                  UserMFA     `protobuf:"varint,14,opt,name=MFA,proto3,enum=idp.UserMFA" json:"MFA,omitempty"`
	MFAKind              UserMFAKind `protobuf:"varint,15,opt,name=MFAKind,proto3,enum=idp.UserMFAKind" json:"MFAKind,omitempty"`
	MFARecover           string      `protobuf:"bytes,16,opt,name=MFARecover,proto3" json:"MFARecover,omitempty"`
	MFAQRCode            string      `protobuf:"bytes,17,opt,name=MFAQRCode,proto3" json:"MFAQRCode,omitempty"`
	Roles                []string    `protobuf:"bytes,18,rep,name=Roles,proto3" json:"Roles,omitempty"`
	Status               UserStatus  `protobuf:"varint,19,opt,name=Status,proto3,enum=idp.UserStatus" json:"Status,omitempty"`
	Birthday             int64       `protobuf:"varint,20,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	CreateTime           int64       `protobuf:"varint,21,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64       `protobuf:"varint,22,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProfileInfo) Reset()         { *m = ProfileInfo{} }
func (m *ProfileInfo) String() string { return proto.CompactTextString(m) }
func (*ProfileInfo) ProtoMessage()    {}
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf7b7d3df3556c9, []int{1}
}

func (m *ProfileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileInfo.Unmarshal(m, b)
}
func (m *ProfileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileInfo.Marshal(b, m, deterministic)
}
func (m *ProfileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileInfo.Merge(m, src)
}
func (m *ProfileInfo) XXX_Size() int {
	return xxx_messageInfo_ProfileInfo.Size(m)
}
func (m *ProfileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileInfo proto.InternalMessageInfo

func (m *ProfileInfo) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *ProfileInfo) GetAppKind() AppKind {
	if m != nil {
		return m.AppKind
	}
	return AppKind_AppKind_Self
}

func (m *ProfileInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ProfileInfo) GetFlag() UserFlag {
	if m != nil {
		return m.Flag
	}
	return UserFlag_UserFlag_UserName
}

func (m *ProfileInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProfileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ProfileInfo) GetMotto() string {
	if m != nil {
		return m.Motto
	}
	return ""
}

func (m *ProfileInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ProfileInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ProfileInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProfileInfo) GetGender() UserGender {
	if m != nil {
		return m.Gender
	}
	return UserGender_UserGender_Girl
}

func (m *ProfileInfo) GetMFA() UserMFA {
	if m != nil {
		return m.MFA
	}
	return UserMFA_UserMFA_Disable
}

func (m *ProfileInfo) GetMFAKind() UserMFAKind {
	if m != nil {
		return m.MFAKind
	}
	return UserMFAKind_UserMFAKind_Phone
}

func (m *ProfileInfo) GetMFARecover() string {
	if m != nil {
		return m.MFARecover
	}
	return ""
}

func (m *ProfileInfo) GetMFAQRCode() string {
	if m != nil {
		return m.MFAQRCode
	}
	return ""
}

func (m *ProfileInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ProfileInfo) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_UserStatus_Normal
}

func (m *ProfileInfo) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *ProfileInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ProfileInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*DeviceInfo)(nil), "idp.DeviceInfo")
	proto.RegisterType((*ProfileInfo)(nil), "idp.ProfileInfo")
}

func init() { proto.RegisterFile("hlm-ipfs/proto/idp/model.proto", fileDescriptor_daf7b7d3df3556c9) }

var fileDescriptor_daf7b7d3df3556c9 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xd5, 0xa6, 0x7f, 0xd6, 0xb3, 0xad, 0x1b, 0xa6, 0x4c, 0x47, 0x13, 0x54, 0x63, 0x17,
	0x80, 0x90, 0x68, 0xa5, 0xf1, 0x04, 0xe9, 0xba, 0xa2, 0x08, 0x65, 0x1b, 0x29, 0xe3, 0x82, 0xbb,
	0x50, 0xbb, 0xd4, 0x22, 0x89, 0x2d, 0xc7, 0xab, 0xc4, 0x2b, 0xf0, 0x4c, 0x3c, 0x1c, 0xf2, 0x71,
	0xd2, 0x06, 0xc4, 0x9d, 0xbf, 0xdf, 0x77, 0xdc, 0xfa, 0xfb, 0x1c, 0xc3, 0x78, 0x93, 0xe5, 0xef,
	0xa4, 0x5e, 0x97, 0x53, 0x6d, 0x94, 0x55, 0x53, 0xc9, 0xf5, 0x34, 0x57, 0x5c, 0x64, 0x13, 0xd2,
	0x2c, 0x90, 0x5c, 0x9f, 0xbf, 0xf8, 0xcf, 0x90, 0x28, 0x1e, 0x73, 0x3f, 0x73, 0xf9, 0xbb, 0x05,
	0x30, 0x17, 0x5b, 0xb9, 0x12, 0x51, 0xb1, 0x56, 0x8c, 0x41, 0x27, 0x8a, 0x6f, 0x22, 0x6c, 0x5d,
	0xb4, 0xde, 0x0c, 0x12, 0x5a, 0xb3, 0x11, 0x74, 0x67, 0x26, 0x2d, 0x38, 0xb6, 0x09, 0x7a, 0xe1,
	0x68, 0xec, 0xfe, 0x0b, 0x03, 0x4f, 0x49, 0xb0, 0x33, 0xe8, 0xdd, 0x2d, 0x6f, 0xd3, 0x5c, 0x60,
	0x87, 0x70, 0xa5, 0xd8, 0x73, 0x18, 0xdc, 0x2d, 0xbf, 0x08, 0x53, 0x4a, 0x55, 0x60, 0x97, 0xac,
	0x3d, 0x60, 0x08, 0xfd, 0x50, 0x6b, 0xda, 0xd6, 0x23, 0xaf, 0x96, 0x6c, 0x0c, 0x10, 0x6a, 0x5d,
	0x6f, 0xec, 0x93, 0xd9, 0x20, 0x97, 0xbf, 0xba, 0x70, 0x78, 0x6f, 0xd4, 0x5a, 0x66, 0xfe, 0xfc,
	0x23, 0xe8, 0x86, 0x5a, 0x47, 0xf3, 0x2a, 0x80, 0x17, 0xec, 0x15, 0xfd, 0xfe, 0x47, 0x59, 0x65,
	0x18, 0x5e, 0x1d, 0x4d, 0x24, 0xd7, 0x93, 0x8a, 0x25, 0xb5, 0xd9, 0x3c, 0x47, 0xf0, 0xf7, 0x39,
	0x5e, 0x42, 0x67, 0x91, 0xa5, 0xdf, 0x29, 0xd5, 0xf0, 0xea, 0x98, 0xb6, 0x3f, 0x94, 0xc2, 0x38,
	0x98, 0x90, 0xc5, 0x86, 0xd0, 0x8e, 0xe6, 0x94, 0x2d, 0x48, 0xda, 0xd1, 0xdc, 0x55, 0xd9, 0x48,
	0x44, 0x6b, 0x76, 0x0e, 0x07, 0xb7, 0x72, 0xf5, 0x83, 0xb8, 0x0f, 0xb3, 0xd3, 0xbe, 0x50, 0x6b,
	0x15, 0x1e, 0xd4, 0x85, 0x5a, 0x4b, 0x81, 0xee, 0x37, 0xaa, 0x10, 0x38, 0xf0, 0x94, 0x84, 0xa3,
	0x37, 0x79, 0x2a, 0x33, 0x04, 0x4f, 0x49, 0xb8, 0xf2, 0xc3, 0x6d, 0x6a, 0x53, 0x83, 0x87, 0xbe,
	0x7c, 0xaf, 0x28, 0x16, 0xe7, 0x46, 0x94, 0x25, 0x1e, 0x55, 0xb1, 0xbc, 0x64, 0xaf, 0xa1, 0xf7,
	0x41, 0x14, 0x5c, 0x18, 0x3c, 0xa6, 0x60, 0x27, 0xbb, 0x60, 0x1e, 0x27, 0x95, 0xcd, 0xc6, 0x10,
	0xc4, 0x8b, 0x10, 0x87, 0x8d, 0xf6, 0xdc, 0x54, 0xbc, 0x08, 0x13, 0x67, 0xb0, 0xb7, 0xd0, 0x8f,
	0x17, 0x21, 0x35, 0x7c, 0x42, 0x33, 0xa7, 0xcd, 0x19, 0xdf, 0x72, 0xb5, 0x70, 0x77, 0xea, 0xf6,
	0x89, 0x95, 0xda, 0x0a, 0x83, 0xa7, 0xfe, 0x4e, 0xf7, 0xc4, 0x7d, 0x2b, 0xf1, 0x22, 0xfc, 0x94,
	0x5c, 0x2b, 0x2e, 0xf0, 0x89, 0xff, 0x56, 0x76, 0xc0, 0x45, 0x4f, 0x54, 0x26, 0x4a, 0x64, 0x17,
	0x81, 0x8b, 0x4e, 0xc2, 0x05, 0x59, 0xda, 0xd4, 0x3e, 0x96, 0xf8, 0xf4, 0x9f, 0x20, 0x1e, 0x27,
	0x95, 0xed, 0x6e, 0x60, 0x26, 0x8d, 0xdd, 0xf0, 0xf4, 0x27, 0x8e, 0xe8, 0xae, 0x76, 0xda, 0x1d,
	0xec, 0xda, 0x88, 0xd4, 0x8a, 0xcf, 0x32, 0x17, 0xf8, 0x8c, 0xdc, 0x06, 0x71, 0xfe, 0x83, 0xe6,
	0xb5, 0x7f, 0xe6, 0xfd, 0x3d, 0x99, 0x75, 0xbf, 0xba, 0x17, 0xf7, 0xad, 0x47, 0x2f, 0xeb, 0xfd,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xa0, 0x73, 0xc9, 0x9f, 0x03, 0x00, 0x00,
}
