// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/market/enum.proto

package market

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BucketStatus int32

const (
	BucketStatus_BucketStatus_Normal BucketStatus = 0
	BucketStatus_BucketStatus_Freeze BucketStatus = 1
)

var BucketStatus_name = map[int32]string{
	0: "BucketStatus_Normal",
	1: "BucketStatus_Freeze",
}

var BucketStatus_value = map[string]int32{
	"BucketStatus_Normal": 0,
	"BucketStatus_Freeze": 1,
}

func (x BucketStatus) String() string {
	return proto.EnumName(BucketStatus_name, int32(x))
}

func (BucketStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ef7bd2e730f52b0, []int{0}
}

type StorageStatus int32

const (
	StorageStatus_StorageStatus_Pending StorageStatus = 0
	StorageStatus_StorageStatus_Running StorageStatus = 1
	StorageStatus_StorageStatus_Finish  StorageStatus = 2
	StorageStatus_StorageStatus_Error   StorageStatus = 3
)

var StorageStatus_name = map[int32]string{
	0: "StorageStatus_Pending",
	1: "StorageStatus_Running",
	2: "StorageStatus_Finish",
	3: "StorageStatus_Error",
}

var StorageStatus_value = map[string]int32{
	"StorageStatus_Pending": 0,
	"StorageStatus_Running": 1,
	"StorageStatus_Finish":  2,
	"StorageStatus_Error":   3,
}

func (x StorageStatus) String() string {
	return proto.EnumName(StorageStatus_name, int32(x))
}

func (StorageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ef7bd2e730f52b0, []int{1}
}

type RetrievalStatus int32

const (
	RetrievalStatus_RetrievalStatus_Starting RetrievalStatus = 0
	RetrievalStatus_RetrievalStatus_Finish   RetrievalStatus = 1
	RetrievalStatus_RetrievalStatus_Error    RetrievalStatus = 2
)

var RetrievalStatus_name = map[int32]string{
	0: "RetrievalStatus_Starting",
	1: "RetrievalStatus_Finish",
	2: "RetrievalStatus_Error",
}

var RetrievalStatus_value = map[string]int32{
	"RetrievalStatus_Starting": 0,
	"RetrievalStatus_Finish":   1,
	"RetrievalStatus_Error":    2,
}

func (x RetrievalStatus) String() string {
	return proto.EnumName(RetrievalStatus_name, int32(x))
}

func (RetrievalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ef7bd2e730f52b0, []int{2}
}

type NodeTaskKind int32

const (
	NodeTaskKind_NodeTaskKind_Storage NodeTaskKind = 0
	NodeTaskKind_NodeTaskKind_Scale   NodeTaskKind = 1
	NodeTaskKind_NodeTaskKind_Migrate NodeTaskKind = 2
	NodeTaskKind_NodeTaskKind_Remove  NodeTaskKind = 3
)

var NodeTaskKind_name = map[int32]string{
	0: "NodeTaskKind_Storage",
	1: "NodeTaskKind_Scale",
	2: "NodeTaskKind_Migrate",
	3: "NodeTaskKind_Remove",
}

var NodeTaskKind_value = map[string]int32{
	"NodeTaskKind_Storage": 0,
	"NodeTaskKind_Scale":   1,
	"NodeTaskKind_Migrate": 2,
	"NodeTaskKind_Remove":  3,
}

func (x NodeTaskKind) String() string {
	return proto.EnumName(NodeTaskKind_name, int32(x))
}

func (NodeTaskKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4ef7bd2e730f52b0, []int{3}
}

func init() {
	proto.RegisterEnum("market.BucketStatus", BucketStatus_name, BucketStatus_value)
	proto.RegisterEnum("market.StorageStatus", StorageStatus_name, StorageStatus_value)
	proto.RegisterEnum("market.RetrievalStatus", RetrievalStatus_name, RetrievalStatus_value)
	proto.RegisterEnum("market.NodeTaskKind", NodeTaskKind_name, NodeTaskKind_value)
}

func init() { proto.RegisterFile("hlm-ipfs/proto/market/enum.proto", fileDescriptor_4ef7bd2e730f52b0) }

var fileDescriptor_4ef7bd2e730f52b0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0x93, 0x16, 0xba, 0xb8, 0xf4, 0xe5, 0x1d, 0xa2, 0xfd, 0x50, 0x5c, 0xb8, 0x0e, 0x68,
	0x16, 0xfe, 0x01, 0x29, 0xd8, 0x8d, 0x58, 0x24, 0x71, 0xe5, 0x26, 0x8c, 0xcd, 0x6d, 0x3a, 0x24,
	0x99, 0x29, 0x77, 0x6e, 0x8a, 0xf8, 0xeb, 0x25, 0x9d, 0x2c, 0x3a, 0xa9, 0xcb, 0x73, 0x1e, 0x98,
	0xe7, 0x5c, 0x06, 0xee, 0xf7, 0x75, 0xf3, 0xa0, 0x0e, 0x3b, 0x9b, 0x1c, 0xc8, 0xb0, 0x49, 0x1a,
	0x49, 0x15, 0x72, 0x82, 0xba, 0x6d, 0x1e, 0x4f, 0x4d, 0x34, 0x71, 0x55, 0xfc, 0x0c, 0xd3, 0x55,
	0xbb, 0xad, 0x90, 0x33, 0x96, 0xdc, 0xda, 0x68, 0x01, 0x57, 0xe7, 0x39, 0xdf, 0x18, 0x6a, 0x64,
	0x2d, 0x82, 0x0b, 0xb0, 0x26, 0xc4, 0x1f, 0x14, 0x61, 0xfc, 0x0d, 0xff, 0x32, 0x36, 0x24, 0x4b,
	0xec, 0x9f, 0xb8, 0x81, 0x99, 0x57, 0xe4, 0xef, 0xa8, 0x0b, 0xa5, 0x4b, 0x11, 0x5c, 0xa2, 0xb4,
	0xd5, 0xba, 0x43, 0x61, 0xb4, 0x84, 0x6b, 0x1f, 0xad, 0x95, 0x56, 0x76, 0x2f, 0x46, 0x9d, 0xd9,
	0x27, 0x2f, 0x44, 0x86, 0xc4, 0x38, 0xde, 0xc1, 0xff, 0x14, 0x99, 0x14, 0x1e, 0x65, 0xdd, 0xbb,
	0xef, 0x60, 0x39, 0xa8, 0xf2, 0x8c, 0x25, 0xb1, 0xd3, 0xdf, 0xc2, 0x7c, 0x48, 0x7b, 0x4b, 0xd8,
	0x4d, 0x1b, 0x32, 0xe7, 0x19, 0xc5, 0x16, 0xa6, 0x1b, 0x53, 0xe0, 0x87, 0xb4, 0xd5, 0xab, 0xd2,
	0x45, 0x37, 0xf5, 0x3c, 0xe7, 0xfd, 0x3a, 0x11, 0x44, 0x73, 0x88, 0x7c, 0xb2, 0x95, 0x35, 0xba,
	0xe3, 0xbc, 0xfe, 0x4d, 0x95, 0x24, 0x19, 0xdd, 0x71, 0x1e, 0x49, 0xb1, 0x31, 0x47, 0x14, 0xe3,
	0xd5, 0xe2, 0x73, 0xf6, 0xe7, 0x27, 0x7e, 0x4d, 0x4e, 0xe9, 0xe9, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x59, 0x23, 0x70, 0x5a, 0xe4, 0x01, 0x00, 0x00,
}
