// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/market/model.retrieval.proto

package market

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basic "hlm-ipfs/sdk/proto/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrievalInfo struct {
	ID                   int64           `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OrderNo              string          `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	AppID                string          `protobuf:"bytes,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID               int64           `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	CID                  string          `protobuf:"bytes,5,opt,name=CID,proto3" json:"CID,omitempty"`
	Name                 string          `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 int64           `protobuf:"varint,7,opt,name=Size,proto3" json:"Size,omitempty"`
	Token                string          `protobuf:"bytes,8,opt,name=Token,proto3" json:"Token,omitempty"`
	Elapsed              float32         `protobuf:"fixed32,9,opt,name=Elapsed,proto3" json:"Elapsed,omitempty"`
	Status               RetrievalStatus `protobuf:"varint,10,opt,name=Status,proto3,enum=market.RetrievalStatus" json:"Status,omitempty"`
	Code                 string          `protobuf:"bytes,11,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string          `protobuf:"bytes,12,opt,name=Msg,proto3" json:"Msg,omitempty"`
	CreateTime           int64           `protobuf:"varint,13,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64           `protobuf:"varint,14,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrievalInfo) Reset()         { *m = RetrievalInfo{} }
func (m *RetrievalInfo) String() string { return proto.CompactTextString(m) }
func (*RetrievalInfo) ProtoMessage()    {}
func (*RetrievalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d36cac42a0830d0, []int{0}
}

func (m *RetrievalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalInfo.Unmarshal(m, b)
}
func (m *RetrievalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalInfo.Marshal(b, m, deterministic)
}
func (m *RetrievalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalInfo.Merge(m, src)
}
func (m *RetrievalInfo) XXX_Size() int {
	return xxx_messageInfo_RetrievalInfo.Size(m)
}
func (m *RetrievalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalInfo proto.InternalMessageInfo

func (m *RetrievalInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RetrievalInfo) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *RetrievalInfo) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *RetrievalInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *RetrievalInfo) GetCID() string {
	if m != nil {
		return m.CID
	}
	return ""
}

func (m *RetrievalInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RetrievalInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RetrievalInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RetrievalInfo) GetElapsed() float32 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *RetrievalInfo) GetStatus() RetrievalStatus {
	if m != nil {
		return m.Status
	}
	return RetrievalStatus_RetrievalStatus_Starting
}

func (m *RetrievalInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RetrievalInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RetrievalInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *RetrievalInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type RetrievalListRequest struct {
	Index                int32         `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Size                 int32         `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	CID                  *basic.String `protobuf:"bytes,11,opt,name=CID,proto3" json:"CID,omitempty"`
	OrderNo              *basic.String `protobuf:"bytes,12,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	Name                 *basic.String `protobuf:"bytes,13,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               *basic.Int32  `protobuf:"bytes,15,opt,name=Status,proto3" json:"Status,omitempty"`
	StartTime            *basic.Int64  `protobuf:"bytes,16,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              *basic.Int64  `protobuf:"bytes,17,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RetrievalListRequest) Reset()         { *m = RetrievalListRequest{} }
func (m *RetrievalListRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievalListRequest) ProtoMessage()    {}
func (*RetrievalListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d36cac42a0830d0, []int{1}
}

func (m *RetrievalListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalListRequest.Unmarshal(m, b)
}
func (m *RetrievalListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalListRequest.Marshal(b, m, deterministic)
}
func (m *RetrievalListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalListRequest.Merge(m, src)
}
func (m *RetrievalListRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievalListRequest.Size(m)
}
func (m *RetrievalListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalListRequest proto.InternalMessageInfo

func (m *RetrievalListRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RetrievalListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RetrievalListRequest) GetCID() *basic.String {
	if m != nil {
		return m.CID
	}
	return nil
}

func (m *RetrievalListRequest) GetOrderNo() *basic.String {
	if m != nil {
		return m.OrderNo
	}
	return nil
}

func (m *RetrievalListRequest) GetName() *basic.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RetrievalListRequest) GetStatus() *basic.Int32 {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RetrievalListRequest) GetStartTime() *basic.Int64 {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *RetrievalListRequest) GetEndTime() *basic.Int64 {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type RetrievalListResponse struct {
	Total                int64            `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Items                []*RetrievalInfo `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RetrievalListResponse) Reset()         { *m = RetrievalListResponse{} }
func (m *RetrievalListResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievalListResponse) ProtoMessage()    {}
func (*RetrievalListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d36cac42a0830d0, []int{2}
}

func (m *RetrievalListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalListResponse.Unmarshal(m, b)
}
func (m *RetrievalListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalListResponse.Marshal(b, m, deterministic)
}
func (m *RetrievalListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalListResponse.Merge(m, src)
}
func (m *RetrievalListResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievalListResponse.Size(m)
}
func (m *RetrievalListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalListResponse proto.InternalMessageInfo

func (m *RetrievalListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RetrievalListResponse) GetItems() []*RetrievalInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type RetrievalCreateResponse struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=Secret,proto3" json:"Secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievalCreateResponse) Reset()         { *m = RetrievalCreateResponse{} }
func (m *RetrievalCreateResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievalCreateResponse) ProtoMessage()    {}
func (*RetrievalCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d36cac42a0830d0, []int{3}
}

func (m *RetrievalCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalCreateResponse.Unmarshal(m, b)
}
func (m *RetrievalCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalCreateResponse.Marshal(b, m, deterministic)
}
func (m *RetrievalCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalCreateResponse.Merge(m, src)
}
func (m *RetrievalCreateResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievalCreateResponse.Size(m)
}
func (m *RetrievalCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalCreateResponse proto.InternalMessageInfo

func (m *RetrievalCreateResponse) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *RetrievalCreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RetrievalCreateResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func init() {
	proto.RegisterType((*RetrievalInfo)(nil), "market.RetrievalInfo")
	proto.RegisterType((*RetrievalListRequest)(nil), "market.RetrievalListRequest")
	proto.RegisterType((*RetrievalListResponse)(nil), "market.RetrievalListResponse")
	proto.RegisterType((*RetrievalCreateResponse)(nil), "market.RetrievalCreateResponse")
}

func init() {
	proto.RegisterFile("hlm-ipfs/proto/market/model.retrieval.proto", fileDescriptor_9d36cac42a0830d0)
}

var fileDescriptor_9d36cac42a0830d0 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0xc6, 0x21, 0x9b, 0x0f, 0xca, 0xaa, 0x69, 0x56, 0x1c, 0xc0, 0x44, 0x08, 0x2c,
	0x2a, 0x1c, 0x29, 0x45, 0xdc, 0x21, 0xee, 0xc1, 0x12, 0x2d, 0x92, 0xdd, 0x5e, 0x7a, 0xdb, 0xd6,
	0xd3, 0x60, 0xc5, 0x5f, 0xec, 0x6e, 0x10, 0xe2, 0x0f, 0xf1, 0xd7, 0xf8, 0x19, 0x68, 0x77, 0x6c,
	0x27, 0x4a, 0x72, 0xb1, 0xf6, 0xcd, 0x7b, 0x9e, 0x9d, 0x79, 0x33, 0x4b, 0x2e, 0x7e, 0x64, 0xf9,
	0xc7, 0xb4, 0x7a, 0x92, 0xf3, 0x4a, 0x94, 0xaa, 0x9c, 0xe7, 0x5c, 0xac, 0x41, 0xcd, 0xf3, 0x32,
	0x81, 0xcc, 0x17, 0xa0, 0x44, 0x0a, 0xbf, 0x78, 0xe6, 0x1b, 0x92, 0x3a, 0xc8, 0xbe, 0x74, 0xf7,
	0x7e, 0x7a, 0xe0, 0x32, 0x7d, 0xc4, 0x2f, 0x2a, 0x0f, 0x14, 0x75, 0x5a, 0x28, 0x36, 0x39, 0x2a,
	0x66, 0xff, 0x6c, 0x32, 0x8a, 0x9a, 0xfc, 0x61, 0xf1, 0x54, 0xd2, 0x31, 0xb1, 0xc3, 0x80, 0x59,
	0xae, 0xe5, 0x75, 0x22, 0x3b, 0x0c, 0x28, 0x23, 0xbd, 0xef, 0x22, 0x01, 0x71, 0x53, 0x32, 0xdb,
	0xb5, 0xbc, 0x7e, 0xd4, 0x40, 0x7a, 0x46, 0xba, 0x5f, 0xaa, 0x2a, 0x0c, 0x58, 0xc7, 0xc4, 0x11,
	0xd0, 0x73, 0xe2, 0xdc, 0x49, 0x10, 0x61, 0xc0, 0x4e, 0x4c, 0x8e, 0x1a, 0xd1, 0x53, 0xd2, 0x59,
	0x86, 0x01, 0xeb, 0x1a, 0xad, 0x3e, 0x52, 0x4a, 0x4e, 0x6e, 0x78, 0x0e, 0xcc, 0x31, 0x21, 0x73,
	0xd6, 0xb1, 0x38, 0xfd, 0x03, 0xac, 0x67, 0xfe, 0x35, 0x67, 0x7d, 0xcf, 0x6d, 0xb9, 0x86, 0x82,
	0x3d, 0xc3, 0x7b, 0x0c, 0xd0, 0x75, 0x5d, 0x65, 0xbc, 0x92, 0x90, 0xb0, 0xbe, 0x6b, 0x79, 0x76,
	0xd4, 0x40, 0x3a, 0x27, 0x4e, 0xac, 0xb8, 0xda, 0x48, 0x46, 0x5c, 0xcb, 0x1b, 0x2f, 0xa6, 0x3e,
	0xf6, 0xed, 0xb7, 0x8d, 0x22, 0x1d, 0xd5, 0x32, 0x7d, 0xe9, 0xb2, 0x4c, 0x80, 0x0d, 0xb0, 0x10,
	0x7d, 0xd6, 0xe5, 0x5e, 0xcb, 0x15, 0x1b, 0x62, 0xb9, 0xd7, 0x72, 0x45, 0x5f, 0x11, 0xb2, 0x14,
	0xc0, 0x15, 0xdc, 0xa6, 0x39, 0xb0, 0x91, 0x29, 0x70, 0x27, 0xa2, 0xf9, 0xbb, 0x2a, 0x69, 0xf8,
	0x31, 0xf2, 0xdb, 0xc8, 0xec, 0xaf, 0x4d, 0xce, 0xda, 0x0a, 0xbe, 0xa5, 0x52, 0x45, 0xf0, 0x73,
	0x03, 0x52, 0xe9, 0xfe, 0xc2, 0x22, 0x81, 0xdf, 0xc6, 0xf4, 0x6e, 0x84, 0xa0, 0x75, 0xc2, 0x36,
	0x41, 0x74, 0xe2, 0x35, 0x7a, 0xa8, 0xeb, 0x1c, 0x2c, 0x46, 0x3e, 0x8e, 0x3a, 0x56, 0x22, 0x2d,
	0x56, 0x68, 0xe9, 0xfb, 0xed, 0xb0, 0x86, 0xc7, 0x44, 0xed, 0xec, 0xde, 0xd4, 0xde, 0x8f, 0x8e,
	0xa9, 0x70, 0x14, 0x6f, 0x5b, 0x1b, 0x9f, 0x1b, 0xd1, 0xb0, 0x16, 0x85, 0x85, 0xba, 0x5c, 0xb4,
	0xde, 0x7d, 0x20, 0xfd, 0x58, 0x71, 0xa1, 0x4c, 0xd3, 0xa7, 0xfb, 0xc2, 0xcf, 0x9f, 0xa2, 0x2d,
	0x4d, 0xdf, 0x91, 0xde, 0x55, 0x91, 0x18, 0xe5, 0x8b, 0x23, 0xca, 0x86, 0x9c, 0xdd, 0x93, 0xc9,
	0x9e, 0x51, 0xb2, 0x2a, 0x0b, 0x59, 0x6f, 0x82, 0xe2, 0x59, 0xbd, 0x9e, 0x08, 0xe8, 0x05, 0xe9,
	0x86, 0x0a, 0x72, 0xc9, 0x6c, 0xb7, 0xe3, 0x0d, 0x16, 0x93, 0x83, 0x71, 0xeb, 0xbd, 0x8e, 0x50,
	0x33, 0xe3, 0x64, 0xda, 0xc6, 0x71, 0x78, 0x6d, 0xf6, 0x9d, 0x4d, 0xb7, 0x0e, 0x36, 0x1d, 0x37,
	0xd0, 0xde, 0xdd, 0xc0, 0x73, 0xe2, 0xc4, 0xf0, 0x28, 0x40, 0xd5, 0x0f, 0xa0, 0x46, 0x5f, 0xa7,
	0xf7, 0x93, 0xa3, 0xef, 0xee, 0xc1, 0x31, 0xe8, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0xc4, 0x11, 0xc7, 0xee, 0x03, 0x00, 0x00,
}
