// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/market/model.bucket.proto

package market

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basic "hlm-ipfs/sdk/proto/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BucketInfo struct {
	ID                   int64        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ParentID             int64        `protobuf:"varint,2,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	AppID                string       `protobuf:"bytes,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID               int64        `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name                 string       `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string       `protobuf:"bytes,6,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Status               BucketStatus `protobuf:"varint,7,opt,name=Status,proto3,enum=market.BucketStatus" json:"Status,omitempty"`
	CreateTime           int64        `protobuf:"varint,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64        `protobuf:"varint,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6a7cbdb4404d16, []int{0}
}

func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BucketInfo) GetParentID() int64 {
	if m != nil {
		return m.ParentID
	}
	return 0
}

func (m *BucketInfo) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *BucketInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *BucketInfo) GetStatus() BucketStatus {
	if m != nil {
		return m.Status
	}
	return BucketStatus_BucketStatus_Normal
}

func (m *BucketInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *BucketInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type BucketNode struct {
	Info                 *BucketInfo   `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Nodes                []*BucketNode `protobuf:"bytes,10,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BucketNode) Reset()         { *m = BucketNode{} }
func (m *BucketNode) String() string { return proto.CompactTextString(m) }
func (*BucketNode) ProtoMessage()    {}
func (*BucketNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6a7cbdb4404d16, []int{1}
}

func (m *BucketNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketNode.Unmarshal(m, b)
}
func (m *BucketNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketNode.Marshal(b, m, deterministic)
}
func (m *BucketNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketNode.Merge(m, src)
}
func (m *BucketNode) XXX_Size() int {
	return xxx_messageInfo_BucketNode.Size(m)
}
func (m *BucketNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketNode.DiscardUnknown(m)
}

var xxx_messageInfo_BucketNode proto.InternalMessageInfo

func (m *BucketNode) GetInfo() *BucketInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *BucketNode) GetNodes() []*BucketNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type BucketNodesResponse struct {
	Nodes                []*BucketNode `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BucketNodesResponse) Reset()         { *m = BucketNodesResponse{} }
func (m *BucketNodesResponse) String() string { return proto.CompactTextString(m) }
func (*BucketNodesResponse) ProtoMessage()    {}
func (*BucketNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6a7cbdb4404d16, []int{2}
}

func (m *BucketNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketNodesResponse.Unmarshal(m, b)
}
func (m *BucketNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketNodesResponse.Marshal(b, m, deterministic)
}
func (m *BucketNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketNodesResponse.Merge(m, src)
}
func (m *BucketNodesResponse) XXX_Size() int {
	return xxx_messageInfo_BucketNodesResponse.Size(m)
}
func (m *BucketNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BucketNodesResponse proto.InternalMessageInfo

func (m *BucketNodesResponse) GetNodes() []*BucketNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type BucketListResponse struct {
	Total                int32         `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Items                []*BucketInfo `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BucketListResponse) Reset()         { *m = BucketListResponse{} }
func (m *BucketListResponse) String() string { return proto.CompactTextString(m) }
func (*BucketListResponse) ProtoMessage()    {}
func (*BucketListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6a7cbdb4404d16, []int{3}
}

func (m *BucketListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketListResponse.Unmarshal(m, b)
}
func (m *BucketListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketListResponse.Marshal(b, m, deterministic)
}
func (m *BucketListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketListResponse.Merge(m, src)
}
func (m *BucketListResponse) XXX_Size() int {
	return xxx_messageInfo_BucketListResponse.Size(m)
}
func (m *BucketListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BucketListResponse proto.InternalMessageInfo

func (m *BucketListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BucketListResponse) GetItems() []*BucketInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type BucketCreateRequest struct {
	ParentID             int64    `protobuf:"varint,1,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketCreateRequest) Reset()         { *m = BucketCreateRequest{} }
func (m *BucketCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BucketCreateRequest) ProtoMessage()    {}
func (*BucketCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6a7cbdb4404d16, []int{4}
}

func (m *BucketCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketCreateRequest.Unmarshal(m, b)
}
func (m *BucketCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketCreateRequest.Marshal(b, m, deterministic)
}
func (m *BucketCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketCreateRequest.Merge(m, src)
}
func (m *BucketCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BucketCreateRequest.Size(m)
}
func (m *BucketCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BucketCreateRequest proto.InternalMessageInfo

func (m *BucketCreateRequest) GetParentID() int64 {
	if m != nil {
		return m.ParentID
	}
	return 0
}

func (m *BucketCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketCreateRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type BucketUpdateRequest struct {
	ID                   int64         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 *basic.String `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 *basic.String `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Status               *basic.Int32  `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	ParentID             *basic.Int64  `protobuf:"bytes,5,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BucketUpdateRequest) Reset()         { *m = BucketUpdateRequest{} }
func (m *BucketUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*BucketUpdateRequest) ProtoMessage()    {}
func (*BucketUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6a7cbdb4404d16, []int{5}
}

func (m *BucketUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketUpdateRequest.Unmarshal(m, b)
}
func (m *BucketUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketUpdateRequest.Marshal(b, m, deterministic)
}
func (m *BucketUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketUpdateRequest.Merge(m, src)
}
func (m *BucketUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_BucketUpdateRequest.Size(m)
}
func (m *BucketUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BucketUpdateRequest proto.InternalMessageInfo

func (m *BucketUpdateRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BucketUpdateRequest) GetName() *basic.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BucketUpdateRequest) GetDesc() *basic.String {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *BucketUpdateRequest) GetStatus() *basic.Int32 {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BucketUpdateRequest) GetParentID() *basic.Int64 {
	if m != nil {
		return m.ParentID
	}
	return nil
}

func init() {
	proto.RegisterType((*BucketInfo)(nil), "market.BucketInfo")
	proto.RegisterType((*BucketNode)(nil), "market.BucketNode")
	proto.RegisterType((*BucketNodesResponse)(nil), "market.BucketNodesResponse")
	proto.RegisterType((*BucketListResponse)(nil), "market.BucketListResponse")
	proto.RegisterType((*BucketCreateRequest)(nil), "market.BucketCreateRequest")
	proto.RegisterType((*BucketUpdateRequest)(nil), "market.BucketUpdateRequest")
}

func init() {
	proto.RegisterFile("hlm-ipfs/proto/market/model.bucket.proto", fileDescriptor_7d6a7cbdb4404d16)
}

var fileDescriptor_7d6a7cbdb4404d16 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb5, 0x4e, 0x6c, 0xda, 0x29, 0xf4, 0xb0, 0x04, 0x58, 0xf5, 0x80, 0x5c, 0x0b, 0x21,
	0x1f, 0xc0, 0x91, 0x52, 0xc4, 0x15, 0x51, 0x7c, 0x59, 0x09, 0x55, 0x68, 0x9b, 0x1e, 0xe0, 0x80,
	0xe4, 0x24, 0x53, 0xb0, 0x1a, 0xff, 0xc1, 0xbb, 0x79, 0x3a, 0x5e, 0x8d, 0x03, 0xda, 0x1d, 0x3b,
	0x4e, 0x9c, 0x48, 0xbd, 0x44, 0x9e, 0xf9, 0x7e, 0xfb, 0xed, 0xcc, 0xce, 0x04, 0xe2, 0xdf, 0xeb,
	0xe2, 0x7d, 0x5e, 0xdf, 0xeb, 0x69, 0xdd, 0x54, 0xa6, 0x9a, 0x16, 0x59, 0xf3, 0x80, 0x66, 0x5a,
	0x54, 0x2b, 0x5c, 0x27, 0x8b, 0xcd, 0xf2, 0x01, 0x4d, 0xe2, 0x14, 0x1e, 0x90, 0x74, 0x11, 0x0e,
	0x4e, 0x2c, 0x32, 0x9d, 0x2f, 0xe9, 0x97, 0xc8, 0x03, 0xa2, 0xf5, 0xc4, 0x72, 0x53, 0x10, 0x11,
	0xfd, 0x63, 0x00, 0xd7, 0xce, 0x5c, 0x96, 0xf7, 0x15, 0x3f, 0x07, 0x4f, 0xa6, 0x82, 0x85, 0x2c,
	0x1e, 0x29, 0x4f, 0xa6, 0xfc, 0x02, 0x4e, 0xbe, 0x65, 0x0d, 0x96, 0x46, 0xa6, 0xc2, 0x73, 0xd9,
	0x6d, 0xcc, 0x27, 0xe0, 0x7f, 0xae, 0x6b, 0x99, 0x8a, 0x51, 0xc8, 0xe2, 0x53, 0x45, 0x01, 0x7f,
	0x09, 0xc1, 0x9d, 0xc6, 0x46, 0xa6, 0x62, 0xec, 0xf8, 0x36, 0xe2, 0x1c, 0xc6, 0x37, 0x59, 0x81,
	0xc2, 0x77, 0xb0, 0xfb, 0xb6, 0xb9, 0x14, 0xf5, 0x52, 0x04, 0x94, 0xb3, 0xdf, 0xfc, 0x1d, 0x04,
	0xb7, 0x26, 0x33, 0x1b, 0x2d, 0x9e, 0x84, 0x2c, 0x3e, 0x9f, 0x4d, 0x12, 0x2a, 0x3a, 0xa1, 0x2a,
	0x49, 0x53, 0x2d, 0xc3, 0x5f, 0x03, 0x7c, 0x69, 0x30, 0x33, 0x38, 0xcf, 0x0b, 0x14, 0x27, 0xee,
	0xc6, 0x9d, 0x8c, 0xd5, 0xef, 0xea, 0x55, 0xa7, 0x9f, 0x92, 0xde, 0x67, 0xa2, 0x9f, 0x5d, 0xf7,
	0x37, 0xd5, 0x0a, 0xf9, 0x5b, 0x18, 0xdb, 0x57, 0x70, 0xfd, 0x9f, 0xcd, 0xf8, 0xfe, 0xcd, 0x56,
	0x51, 0x4e, 0xe7, 0x31, 0xf8, 0x96, 0xd7, 0x02, 0xc2, 0xd1, 0x21, 0x68, 0x25, 0x45, 0x40, 0xf4,
	0x09, 0x9e, 0xf7, 0x49, 0xad, 0x50, 0xd7, 0x55, 0xa9, 0xb1, 0x37, 0x60, 0x8f, 0x19, 0xcc, 0x81,
	0x53, 0xf2, 0x6b, 0xae, 0xcd, 0xf6, 0xfc, 0x04, 0xfc, 0x79, 0x65, 0xb2, 0xb5, 0xab, 0xd4, 0x57,
	0x14, 0x58, 0x57, 0x69, 0xb0, 0xd0, 0xc2, 0x3b, 0xe6, 0xea, 0xea, 0x27, 0x20, 0xfa, 0xde, 0x95,
	0x45, 0x4f, 0xa5, 0xf0, 0xcf, 0x06, 0xb5, 0xd9, 0x9b, 0x36, 0x1b, 0x4c, 0xbb, 0x9b, 0x9f, 0x77,
	0x64, 0x7e, 0xa3, 0x7e, 0x7e, 0xd1, 0x5f, 0xd6, 0x79, 0xd3, 0x33, 0x77, 0xde, 0xc3, 0xcd, 0xba,
	0xdc, 0xf1, 0x3b, 0x9b, 0x3d, 0x4b, 0x68, 0x6d, 0x6f, 0x4d, 0x93, 0x97, 0xbf, 0x5a, 0xfb, 0xcb,
	0x1d, 0xfb, 0x43, 0xc4, 0x6d, 0xcb, 0x9b, 0xed, 0xb6, 0x8c, 0x1d, 0xf4, 0xb4, 0x85, 0x64, 0x69,
	0xae, 0x66, 0xdb, 0x2d, 0x89, 0x77, 0xfa, 0xf2, 0x87, 0xdc, 0xc7, 0x0f, 0x7d, 0x97, 0xd7, 0xaf,
	0x7e, 0xbc, 0x38, 0xfa, 0x97, 0x59, 0x04, 0x2e, 0xba, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xd5,
	0xdd, 0x2d, 0xa1, 0xa6, 0x03, 0x00, 0x00,
}
