// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/market/model.proto

package market

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "hlm-ipfs/sdk/proto/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeTask struct {
	Kind                 NodeTaskKind `protobuf:"varint,1,opt,name=Kind,proto3,enum=market.NodeTaskKind" json:"Kind,omitempty"`
	ObjectID             int64        `protobuf:"varint,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	CIDs                 []string     `protobuf:"bytes,3,rep,name=CIDs,proto3" json:"CIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NodeTask) Reset()         { *m = NodeTask{} }
func (m *NodeTask) String() string { return proto.CompactTextString(m) }
func (*NodeTask) ProtoMessage()    {}
func (*NodeTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fd68401ce78cdf, []int{0}
}

func (m *NodeTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeTask.Unmarshal(m, b)
}
func (m *NodeTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeTask.Marshal(b, m, deterministic)
}
func (m *NodeTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeTask.Merge(m, src)
}
func (m *NodeTask) XXX_Size() int {
	return xxx_messageInfo_NodeTask.Size(m)
}
func (m *NodeTask) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeTask.DiscardUnknown(m)
}

var xxx_messageInfo_NodeTask proto.InternalMessageInfo

func (m *NodeTask) GetKind() NodeTaskKind {
	if m != nil {
		return m.Kind
	}
	return NodeTaskKind_NodeTaskKind_Storage
}

func (m *NodeTask) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *NodeTask) GetCIDs() []string {
	if m != nil {
		return m.CIDs
	}
	return nil
}

type CountResponse struct {
	FileCount            int64    `protobuf:"varint,1,opt,name=FileCount,proto3" json:"FileCount,omitempty"`
	TotalSize            int64    `protobuf:"varint,2,opt,name=TotalSize,proto3" json:"TotalSize,omitempty"`
	RetrievalCount       int64    `protobuf:"varint,3,opt,name=RetrievalCount,proto3" json:"RetrievalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8fd68401ce78cdf, []int{1}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetFileCount() int64 {
	if m != nil {
		return m.FileCount
	}
	return 0
}

func (m *CountResponse) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *CountResponse) GetRetrievalCount() int64 {
	if m != nil {
		return m.RetrievalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*NodeTask)(nil), "market.NodeTask")
	proto.RegisterType((*CountResponse)(nil), "market.CountResponse")
}

func init() { proto.RegisterFile("hlm-ipfs/proto/market/model.proto", fileDescriptor_d8fd68401ce78cdf) }

var fileDescriptor_d8fd68401ce78cdf = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0x53, 0x4a, 0x7b, 0xc1, 0x2e, 0x82, 0xe2, 0x50, 0x5c, 0xc4, 0x2e, 0x24, 0x1b,
	0x67, 0x40, 0xdf, 0xc0, 0x16, 0xa1, 0x08, 0x0a, 0xb1, 0x2b, 0x77, 0x99, 0xe6, 0x8a, 0xb1, 0xf9,
	0x19, 0x26, 0xa9, 0x0b, 0x9f, 0x5e, 0x9a, 0x54, 0x07, 0x46, 0x37, 0x21, 0xe7, 0x3b, 0x1f, 0x27,
	0x04, 0xae, 0xde, 0x8d, 0xbd, 0xd1, 0xed, 0x5b, 0xa8, 0xdb, 0xce, 0x47, 0x5f, 0x5b, 0xd9, 0xed,
	0x30, 0xd6, 0xd6, 0x2b, 0x34, 0x55, 0x42, 0x74, 0x9c, 0xd9, 0x9c, 0x0d, 0xd4, 0x46, 0x06, 0xbd,
	0xcd, 0x67, 0x36, 0xff, 0x18, 0xc7, 0x31, 0x74, 0x7b, 0x9b, 0x8d, 0x85, 0x82, 0xc9, 0x93, 0x57,
	0xb8, 0x91, 0x61, 0x47, 0x39, 0x8c, 0x1e, 0xb5, 0x53, 0x65, 0xc1, 0x0a, 0x3e, 0xbb, 0x3d, 0xab,
	0xb2, 0x5d, 0xfd, 0xf4, 0x87, 0x4e, 0x24, 0x83, 0xce, 0x61, 0xf2, 0xdc, 0x7c, 0xe0, 0x36, 0xae,
	0x57, 0xe5, 0x09, 0x2b, 0x38, 0x11, 0xbf, 0x99, 0x52, 0x18, 0x2d, 0xd7, 0xab, 0x50, 0x12, 0x46,
	0xf8, 0x54, 0xa4, 0xfb, 0x22, 0xc0, 0xe9, 0xd2, 0xef, 0x5d, 0x14, 0x18, 0x5a, 0xef, 0x02, 0xd2,
	0x4b, 0x98, 0x3e, 0x68, 0x83, 0x09, 0xa6, 0xf7, 0x88, 0xe8, 0xc1, 0xa1, 0xdd, 0xf8, 0x28, 0xcd,
	0x8b, 0xfe, 0xc2, 0xe3, 0x7e, 0x0f, 0xe8, 0x35, 0xcc, 0x04, 0xc6, 0x4e, 0xe3, 0xa7, 0x34, 0x79,
	0x80, 0x24, 0x65, 0x40, 0xef, 0x2f, 0x5e, 0xcf, 0xff, 0xfd, 0x7e, 0x33, 0x4e, 0xe9, 0xee, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0x47, 0x68, 0xee, 0x6b, 0x01, 0x00, 0x00,
}
