// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hlm-ipfs/proto/market/model.storage.proto

package market

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basic "hlm-ipfs/sdk/proto/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageInfo struct {
	ID                   int64         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OrderNo              string        `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	AppID                string        `protobuf:"bytes,3,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID               int64         `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BucketID             int64         `protobuf:"varint,5,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CID                  string        `protobuf:"bytes,6,opt,name=CID,proto3" json:"CID,omitempty"`
	Name                 string        `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 int64         `protobuf:"varint,8,opt,name=Size,proto3" json:"Size,omitempty"`
	Tags                 []string      `protobuf:"bytes,9,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Replica              int32         `protobuf:"varint,10,opt,name=Replica,proto3" json:"Replica,omitempty"`
	Duration             int64         `protobuf:"varint,11,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Status               StorageStatus `protobuf:"varint,12,opt,name=Status,proto3,enum=market.StorageStatus" json:"Status,omitempty"`
	Code                 string        `protobuf:"bytes,13,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string        `protobuf:"bytes,14,opt,name=Msg,proto3" json:"Msg,omitempty"`
	CreateTime           int64         `protobuf:"varint,15,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           int64         `protobuf:"varint,16,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	Filecoin             *FilecoinInfo `protobuf:"bytes,20,opt,name=Filecoin,proto3" json:"Filecoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageInfo) Reset()         { *m = StorageInfo{} }
func (m *StorageInfo) String() string { return proto.CompactTextString(m) }
func (*StorageInfo) ProtoMessage()    {}
func (*StorageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9be332bf95172f, []int{0}
}

func (m *StorageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageInfo.Unmarshal(m, b)
}
func (m *StorageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageInfo.Marshal(b, m, deterministic)
}
func (m *StorageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageInfo.Merge(m, src)
}
func (m *StorageInfo) XXX_Size() int {
	return xxx_messageInfo_StorageInfo.Size(m)
}
func (m *StorageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StorageInfo proto.InternalMessageInfo

func (m *StorageInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *StorageInfo) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *StorageInfo) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *StorageInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *StorageInfo) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *StorageInfo) GetCID() string {
	if m != nil {
		return m.CID
	}
	return ""
}

func (m *StorageInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StorageInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StorageInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StorageInfo) GetReplica() int32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *StorageInfo) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *StorageInfo) GetStatus() StorageStatus {
	if m != nil {
		return m.Status
	}
	return StorageStatus_StorageStatus_Pending
}

func (m *StorageInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *StorageInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *StorageInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *StorageInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *StorageInfo) GetFilecoin() *FilecoinInfo {
	if m != nil {
		return m.Filecoin
	}
	return nil
}

type StorageListRequest struct {
	Index                int32         `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Size                 int32         `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	BucketID             *basic.Int64  `protobuf:"bytes,10,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CID                  *basic.String `protobuf:"bytes,11,opt,name=CID,proto3" json:"CID,omitempty"`
	OrderNo              *basic.String `protobuf:"bytes,12,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	Name                 *basic.String `protobuf:"bytes,13,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag                  *basic.String `protobuf:"bytes,14,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Status               *basic.Int32  `protobuf:"bytes,15,opt,name=Status,proto3" json:"Status,omitempty"`
	StartTime            *basic.Int64  `protobuf:"bytes,16,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              *basic.Int64  `protobuf:"bytes,17,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageListRequest) Reset()         { *m = StorageListRequest{} }
func (m *StorageListRequest) String() string { return proto.CompactTextString(m) }
func (*StorageListRequest) ProtoMessage()    {}
func (*StorageListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9be332bf95172f, []int{1}
}

func (m *StorageListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageListRequest.Unmarshal(m, b)
}
func (m *StorageListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageListRequest.Marshal(b, m, deterministic)
}
func (m *StorageListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageListRequest.Merge(m, src)
}
func (m *StorageListRequest) XXX_Size() int {
	return xxx_messageInfo_StorageListRequest.Size(m)
}
func (m *StorageListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageListRequest proto.InternalMessageInfo

func (m *StorageListRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StorageListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StorageListRequest) GetBucketID() *basic.Int64 {
	if m != nil {
		return m.BucketID
	}
	return nil
}

func (m *StorageListRequest) GetCID() *basic.String {
	if m != nil {
		return m.CID
	}
	return nil
}

func (m *StorageListRequest) GetOrderNo() *basic.String {
	if m != nil {
		return m.OrderNo
	}
	return nil
}

func (m *StorageListRequest) GetName() *basic.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *StorageListRequest) GetTag() *basic.String {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *StorageListRequest) GetStatus() *basic.Int32 {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StorageListRequest) GetStartTime() *basic.Int64 {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *StorageListRequest) GetEndTime() *basic.Int64 {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type StorageListResponse struct {
	Total                int64          `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Items                []*StorageInfo `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StorageListResponse) Reset()         { *m = StorageListResponse{} }
func (m *StorageListResponse) String() string { return proto.CompactTextString(m) }
func (*StorageListResponse) ProtoMessage()    {}
func (*StorageListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9be332bf95172f, []int{2}
}

func (m *StorageListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageListResponse.Unmarshal(m, b)
}
func (m *StorageListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageListResponse.Marshal(b, m, deterministic)
}
func (m *StorageListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageListResponse.Merge(m, src)
}
func (m *StorageListResponse) XXX_Size() int {
	return xxx_messageInfo_StorageListResponse.Size(m)
}
func (m *StorageListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageListResponse proto.InternalMessageInfo

func (m *StorageListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *StorageListResponse) GetItems() []*StorageInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type StorageCreateRequest struct {
	BucketID             int64         `protobuf:"varint,5,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CID                  string        `protobuf:"bytes,6,opt,name=CID,proto3" json:"CID,omitempty"`
	Name                 string        `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 int64         `protobuf:"varint,8,opt,name=Size,proto3" json:"Size,omitempty"`
	Secret               string        `protobuf:"bytes,9,opt,name=Secret,proto3" json:"Secret,omitempty"`
	Tags                 []string      `protobuf:"bytes,10,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Replica              int32         `protobuf:"varint,11,opt,name=Replica,proto3" json:"Replica,omitempty"`
	Duration             int64         `protobuf:"varint,12,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Filecoin             *FilecoinInfo `protobuf:"bytes,20,opt,name=Filecoin,proto3" json:"Filecoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StorageCreateRequest) Reset()         { *m = StorageCreateRequest{} }
func (m *StorageCreateRequest) String() string { return proto.CompactTextString(m) }
func (*StorageCreateRequest) ProtoMessage()    {}
func (*StorageCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9be332bf95172f, []int{3}
}

func (m *StorageCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageCreateRequest.Unmarshal(m, b)
}
func (m *StorageCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageCreateRequest.Marshal(b, m, deterministic)
}
func (m *StorageCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageCreateRequest.Merge(m, src)
}
func (m *StorageCreateRequest) XXX_Size() int {
	return xxx_messageInfo_StorageCreateRequest.Size(m)
}
func (m *StorageCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageCreateRequest proto.InternalMessageInfo

func (m *StorageCreateRequest) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *StorageCreateRequest) GetCID() string {
	if m != nil {
		return m.CID
	}
	return ""
}

func (m *StorageCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StorageCreateRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StorageCreateRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *StorageCreateRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StorageCreateRequest) GetReplica() int32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

func (m *StorageCreateRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *StorageCreateRequest) GetFilecoin() *FilecoinInfo {
	if m != nil {
		return m.Filecoin
	}
	return nil
}

type StorageUpdateRequest struct {
	OrderNo              string         `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	BucketID             *basic.Int64   `protobuf:"bytes,10,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Name                 *basic.String  `protobuf:"bytes,11,opt,name=Name,proto3" json:"Name,omitempty"`
	Tags                 *basic.Strings `protobuf:"bytes,12,opt,name=Tags,proto3" json:"Tags,omitempty"`
	Replica              *basic.Int32   `protobuf:"bytes,13,opt,name=Replica,proto3" json:"Replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StorageUpdateRequest) Reset()         { *m = StorageUpdateRequest{} }
func (m *StorageUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*StorageUpdateRequest) ProtoMessage()    {}
func (*StorageUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9be332bf95172f, []int{4}
}

func (m *StorageUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageUpdateRequest.Unmarshal(m, b)
}
func (m *StorageUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageUpdateRequest.Marshal(b, m, deterministic)
}
func (m *StorageUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageUpdateRequest.Merge(m, src)
}
func (m *StorageUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_StorageUpdateRequest.Size(m)
}
func (m *StorageUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageUpdateRequest proto.InternalMessageInfo

func (m *StorageUpdateRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *StorageUpdateRequest) GetBucketID() *basic.Int64 {
	if m != nil {
		return m.BucketID
	}
	return nil
}

func (m *StorageUpdateRequest) GetName() *basic.String {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *StorageUpdateRequest) GetTags() *basic.Strings {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StorageUpdateRequest) GetReplica() *basic.Int32 {
	if m != nil {
		return m.Replica
	}
	return nil
}

type FilecoinInfo struct {
	Enable               bool     `protobuf:"varint,1,opt,name=Enable,proto3" json:"Enable,omitempty"`
	MinerIDs             []string `protobuf:"bytes,2,rep,name=MinerIDs,proto3" json:"MinerIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilecoinInfo) Reset()         { *m = FilecoinInfo{} }
func (m *FilecoinInfo) String() string { return proto.CompactTextString(m) }
func (*FilecoinInfo) ProtoMessage()    {}
func (*FilecoinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9be332bf95172f, []int{5}
}

func (m *FilecoinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilecoinInfo.Unmarshal(m, b)
}
func (m *FilecoinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilecoinInfo.Marshal(b, m, deterministic)
}
func (m *FilecoinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilecoinInfo.Merge(m, src)
}
func (m *FilecoinInfo) XXX_Size() int {
	return xxx_messageInfo_FilecoinInfo.Size(m)
}
func (m *FilecoinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FilecoinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FilecoinInfo proto.InternalMessageInfo

func (m *FilecoinInfo) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *FilecoinInfo) GetMinerIDs() []string {
	if m != nil {
		return m.MinerIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageInfo)(nil), "market.StorageInfo")
	proto.RegisterType((*StorageListRequest)(nil), "market.StorageListRequest")
	proto.RegisterType((*StorageListResponse)(nil), "market.StorageListResponse")
	proto.RegisterType((*StorageCreateRequest)(nil), "market.StorageCreateRequest")
	proto.RegisterType((*StorageUpdateRequest)(nil), "market.StorageUpdateRequest")
	proto.RegisterType((*FilecoinInfo)(nil), "market.FilecoinInfo")
}

func init() {
	proto.RegisterFile("hlm-ipfs/proto/market/model.storage.proto", fileDescriptor_8e9be332bf95172f)
}

var fileDescriptor_8e9be332bf95172f = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0xb5, 0x6b, 0x6f, 0xda, 0x6e, 0x78, 0xdd, 0xb0, 0xf6, 0xc0, 0x42, 0x85, 0x46,
	0x86, 0xb4, 0x0e, 0x75, 0x88, 0x77, 0xb6, 0x0c, 0x29, 0x12, 0x1b, 0x52, 0xda, 0xf1, 0xc0, 0x9b,
	0xd7, 0x7a, 0x25, 0x5a, 0xf3, 0x41, 0xec, 0x4a, 0x88, 0x27, 0xfe, 0x1e, 0x12, 0x3f, 0x86, 0x9f,
	0x80, 0xec, 0xeb, 0xa4, 0x5d, 0xd7, 0x49, 0xf0, 0xc0, 0x4b, 0xe4, 0x7b, 0xef, 0x89, 0x7d, 0x7d,
	0xce, 0xb9, 0x86, 0xa3, 0x2f, 0xb3, 0xe4, 0x38, 0xce, 0x6f, 0xc5, 0x49, 0x5e, 0x64, 0x32, 0x3b,
	0x49, 0x58, 0x71, 0xc7, 0xe5, 0x49, 0x92, 0x4d, 0xf8, 0xac, 0x2f, 0x64, 0x56, 0xb0, 0x29, 0xef,
	0xeb, 0x12, 0xa9, 0x63, 0x6d, 0xdf, 0x5b, 0xf9, 0xe5, 0x86, 0x89, 0x78, 0x8c, 0x5f, 0x44, 0x3e,
	0x40, 0x98, 0x4d, 0x79, 0x3a, 0x4f, 0x10, 0xd1, 0xfb, 0xe5, 0x80, 0x3b, 0xc4, 0xdd, 0xc3, 0xf4,
	0x36, 0x23, 0x1d, 0xb0, 0xc3, 0x80, 0x5a, 0x9e, 0xe5, 0x3b, 0x91, 0x1d, 0x06, 0x84, 0xc2, 0xe6,
	0xc7, 0x62, 0xc2, 0x8b, 0xab, 0x8c, 0xda, 0x9e, 0xe5, 0x37, 0xa3, 0x32, 0x24, 0x5d, 0xa8, 0xbd,
	0xcb, 0xf3, 0x30, 0xa0, 0x8e, 0xce, 0x63, 0x40, 0xf6, 0xa0, 0x7e, 0x2d, 0x78, 0x11, 0x06, 0x74,
	0x43, 0xef, 0x61, 0x22, 0xb2, 0x0f, 0x8d, 0xb3, 0xf9, 0xf8, 0x8e, 0xcb, 0x30, 0xa0, 0x35, 0x5d,
	0xa9, 0x62, 0xb2, 0x0d, 0xce, 0x79, 0x18, 0xd0, 0xba, 0xde, 0x47, 0x2d, 0x09, 0x81, 0x8d, 0x2b,
	0x96, 0x70, 0xba, 0xa9, 0x53, 0x7a, 0xad, 0x72, 0xc3, 0xf8, 0x3b, 0xa7, 0x0d, 0xfd, 0xb7, 0x5e,
	0xab, 0xdc, 0x88, 0x4d, 0x05, 0x6d, 0x7a, 0x8e, 0xc2, 0xa9, 0xb5, 0xea, 0x38, 0xe2, 0xf9, 0x2c,
	0x1e, 0x33, 0x0a, 0x9e, 0xe5, 0xd7, 0xa2, 0x32, 0x54, 0x3d, 0x04, 0xf3, 0x82, 0xc9, 0x38, 0x4b,
	0xa9, 0x8b, 0x3d, 0x94, 0x31, 0x39, 0x86, 0xfa, 0x50, 0x32, 0x39, 0x17, 0xb4, 0xe5, 0x59, 0x7e,
	0x67, 0xb0, 0xdb, 0x47, 0xae, 0xfa, 0x86, 0x1c, 0x2c, 0x46, 0x06, 0xa4, 0x0e, 0x3e, 0xcf, 0x26,
	0x9c, 0xb6, 0xb1, 0x41, 0xb5, 0x56, 0xd7, 0xb8, 0x14, 0x53, 0xda, 0xc1, 0x6b, 0x5c, 0x8a, 0x29,
	0x79, 0x06, 0x70, 0x5e, 0x70, 0x26, 0xf9, 0x28, 0x4e, 0x38, 0xdd, 0xd2, 0x47, 0x2e, 0x65, 0x54,
	0xfd, 0x3a, 0x9f, 0x94, 0xf5, 0x6d, 0xac, 0x2f, 0x32, 0xe4, 0x35, 0x34, 0xde, 0xc7, 0x33, 0x3e,
	0xce, 0xe2, 0x94, 0x76, 0x3d, 0xcb, 0x77, 0x07, 0xdd, 0xb2, 0xad, 0x32, 0xaf, 0x44, 0x8b, 0x2a,
	0x54, 0xef, 0xb7, 0x0d, 0xc4, 0x74, 0xfc, 0x21, 0x16, 0x32, 0xe2, 0x5f, 0xe7, 0x5c, 0x48, 0xa5,
	0x55, 0x98, 0x4e, 0xf8, 0x37, 0x2d, 0x6c, 0x2d, 0xc2, 0xa0, 0x62, 0xd4, 0xd6, 0x49, 0x64, 0xd4,
	0x5f, 0xd2, 0x09, 0xf4, 0x91, 0xad, 0x3e, 0x3a, 0x2a, 0x4c, 0xe5, 0xdb, 0x37, 0x4b, 0xaa, 0x1d,
	0xa0, 0x6a, 0xae, 0x06, 0xb5, 0x0d, 0x68, 0x28, 0x8b, 0x38, 0x9d, 0xa2, 0x88, 0x2f, 0x17, 0xd6,
	0x69, 0xad, 0x03, 0x55, 0x4e, 0x7a, 0x6e, 0xd4, 0x6e, 0xaf, 0x43, 0xa1, 0xf8, 0x07, 0xe0, 0x8c,
	0x18, 0x72, 0xfb, 0xf0, 0xb0, 0x11, 0x9b, 0x92, 0x17, 0x95, 0x7e, 0x5b, 0xab, 0x5d, 0x9f, 0x0e,
	0x2a, 0xd9, 0x5e, 0x41, 0x73, 0x28, 0x59, 0x21, 0x2b, 0xbe, 0x57, 0xaf, 0xb7, 0x28, 0x93, 0x43,
	0xd8, 0xbc, 0x48, 0x27, 0x1a, 0xf9, 0x64, 0x0d, 0xb2, 0x2c, 0xf6, 0x3e, 0xc1, 0xce, 0x3d, 0xc6,
	0x45, 0x9e, 0xa5, 0x82, 0x2b, 0xca, 0x47, 0x99, 0x64, 0x33, 0x33, 0x4b, 0x18, 0x90, 0x23, 0xa8,
	0x85, 0x92, 0x27, 0x82, 0xda, 0x9e, 0xe3, 0xbb, 0x83, 0x9d, 0x15, 0x97, 0x69, 0x35, 0x11, 0xd1,
	0xfb, 0x61, 0x43, 0xd7, 0xa4, 0xd1, 0x32, 0xa5, 0x98, 0xff, 0x67, 0x94, 0xf6, 0xa0, 0x3e, 0xe4,
	0xe3, 0x82, 0x4b, 0xda, 0xd4, 0x48, 0x13, 0x55, 0x23, 0x06, 0xeb, 0x47, 0xcc, 0x7d, 0x7c, 0xc4,
	0x5a, 0x2b, 0x23, 0xf6, 0xef, 0x6e, 0xfe, 0x69, 0x55, 0x14, 0xe0, 0x54, 0x94, 0x14, 0x2c, 0xbd,
	0x4a, 0xd6, 0xfd, 0x57, 0xe9, 0xef, 0xfd, 0x5b, 0xba, 0xce, 0x7d, 0xdc, 0x75, 0x3d, 0x73, 0x77,
	0xb4, 0x6f, 0xe7, 0x1e, 0x44, 0x18, 0x2e, 0x0e, 0x17, 0x5c, 0xb4, 0xd7, 0x38, 0xaf, 0x2c, 0xf6,
	0xce, 0xa0, 0xb5, 0x7c, 0x4b, 0xc5, 0xf7, 0x45, 0xca, 0x6e, 0x66, 0x5c, 0xdf, 0xa0, 0x11, 0x99,
	0x48, 0x31, 0x78, 0x19, 0xa7, 0xea, 0xcd, 0x44, 0x93, 0x34, 0xa3, 0x2a, 0x3e, 0x7b, 0xfa, 0x79,
	0x77, 0xed, 0x83, 0x7e, 0x53, 0xd7, 0xd1, 0xe9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x4a,
	0xd8, 0xb3, 0x45, 0x06, 0x00, 0x00,
}
